
// This file has been generated by the GUI designer. Do not modify.
namespace RestrictionTrackerGTK
{
	public partial class dlgAlertSelection
	{
		private global::Gtk.HBox pnlList;

		private global::Gtk.VBox pnlListBox;

		private global::Gtk.HBox pnlListButtons;

		private global::Gtk.Button cmdAdd;

		private global::Gtk.Button cmdRemove;

		private global::Gtk.EventBox evntPreview;

		private global::Gtk.Image pctPreview;

		private global::Gtk.Label lblMore;

		private global::Gtk.VSeparator vsButtons;

		private global::Gtk.Button cmdSave;

		private global::Gtk.Button cmdClose;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RestrictionTrackerGTK.dlgAlertSelection
			this.Name = "RestrictionTrackerGTK.dlgAlertSelection";
			this.Title = global::Mono.Unix.Catalog.GetString("Select Alert Window Style");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("RestrictionTrackerGTK.Resources.norm.ico");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Internal child RestrictionTrackerGTK.dlgAlertSelection.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "pnlStyles";
			w1.BorderWidth = ((uint)(2));
			// Container child pnlStyles.Gtk.Box+BoxChild
			this.pnlList = new global::Gtk.HBox();
			this.pnlList.Name = "pnlList";
			this.pnlList.Spacing = 6;
			// Container child pnlList.Gtk.Box+BoxChild
			this.pnlListBox = new global::Gtk.VBox();
			this.pnlListBox.Name = "pnlListBox";
			this.pnlListBox.Spacing = 6;
			// Container child pnlListBox.Gtk.Box+BoxChild
			this.pnlListButtons = new global::Gtk.HBox();
			this.pnlListButtons.Name = "pnlListButtons";
			this.pnlListButtons.Homogeneous = true;
			this.pnlListButtons.Spacing = 6;
			// Container child pnlListButtons.Gtk.Box+BoxChild
			this.cmdAdd = new global::Gtk.Button();
			this.cmdAdd.CanFocus = true;
			this.cmdAdd.Name = "cmdAdd";
			this.cmdAdd.UseUnderline = true;
			this.cmdAdd.Label = global::Mono.Unix.Catalog.GetString("_Add");
			this.pnlListButtons.Add(this.cmdAdd);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.pnlListButtons[this.cmdAdd]));
			w2.Position = 0;
			// Container child pnlListButtons.Gtk.Box+BoxChild
			this.cmdRemove = new global::Gtk.Button();
			this.cmdRemove.CanFocus = true;
			this.cmdRemove.Name = "cmdRemove";
			this.cmdRemove.UseUnderline = true;
			this.cmdRemove.Label = global::Mono.Unix.Catalog.GetString("_Remove");
			this.pnlListButtons.Add(this.cmdRemove);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.pnlListButtons[this.cmdRemove]));
			w3.Position = 1;
			this.pnlListBox.Add(this.pnlListButtons);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.pnlListBox[this.pnlListButtons]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.pnlList.Add(this.pnlListBox);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.pnlList[this.pnlListBox]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child pnlList.Gtk.Box+BoxChild
			this.evntPreview = new global::Gtk.EventBox();
			this.evntPreview.Name = "evntPreview";
			// Container child evntPreview.Gtk.Container+ContainerChild
			this.pctPreview = new global::Gtk.Image();
			this.pctPreview.TooltipMarkup = "Preview the selected Alert Window Style.\n<b>Middle Click:</b> Popup a live Alert " +
				"Window using the selected style.\n<b>Right Click:</b> Copy the preview to the Cli" +
				"pboard as an image.";
			this.pctPreview.Name = "pctPreview";
			this.pctPreview.Xalign = 1F;
			this.evntPreview.Add(this.pctPreview);
			this.pnlList.Add(this.evntPreview);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.pnlList[this.evntPreview]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			w1.Add(this.pnlList);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1[this.pnlList]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Internal child RestrictionTrackerGTK.dlgAlertSelection.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "pnlButtons";
			w9.Spacing = 10;
			w9.BorderWidth = ((uint)(5));
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child pnlButtons.Gtk.ButtonBox+ButtonBoxChild
			this.lblMore = new global::Gtk.Label();
			this.lblMore.CanFocus = true;
			this.lblMore.Name = "lblMore";
			this.lblMore.LabelProp = global::Mono.Unix.Catalog.GetString("Get More Styles");
			w9.Add(this.lblMore);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9[this.lblMore]));
			w10.Expand = false;
			w10.Fill = false;
			// Container child pnlButtons.Gtk.ButtonBox+ButtonBoxChild
			this.vsButtons = new global::Gtk.VSeparator();
			this.vsButtons.Name = "vsButtons";
			w9.Add(this.vsButtons);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9[this.vsButtons]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child pnlButtons.Gtk.ButtonBox+ButtonBoxChild
			this.cmdSave = new global::Gtk.Button();
			this.cmdSave.TooltipMarkup = "Save your Alert Window Style selection.";
			this.cmdSave.CanDefault = true;
			this.cmdSave.CanFocus = true;
			this.cmdSave.Name = "cmdSave";
			this.cmdSave.UseUnderline = true;
			this.cmdSave.Label = global::Mono.Unix.Catalog.GetString("_Save");
			w9.Add(this.cmdSave);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9[this.cmdSave]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child pnlButtons.Gtk.ButtonBox+ButtonBoxChild
			this.cmdClose = new global::Gtk.Button();
			this.cmdClose.TooltipMarkup = "Close the Select Alert Style window.";
			this.cmdClose.CanDefault = true;
			this.cmdClose.CanFocus = true;
			this.cmdClose.Name = "cmdClose";
			this.cmdClose.UseUnderline = true;
			this.cmdClose.Label = global::Mono.Unix.Catalog.GetString("_Close");
			w9.Add(this.cmdClose);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9[this.cmdClose]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 484;
			this.DefaultHeight = 91;
			this.Hide();
			this.cmdAdd.Clicked += new global::System.EventHandler(this.cmdAdd_Clicked);
			this.cmdRemove.Clicked += new global::System.EventHandler(this.cmdRemove_Clicked);
		}
	}
}
