
// This file has been generated by the GUI designer. Do not modify.
namespace RestrictionTrackerGTK
{
	public partial class frmMain
	{
		private global::Gtk.VBox pnlDetails;

		private global::Gtk.HBox pnlButtons;

		private global::Gtk.Button cmdRefresh;

		private global::Gtk.Button cmdHistory;

		private global::Gtk.Button cmdConfig;

		private global::Gtk.Button cmdAbout;

		private global::Gtk.Frame gbUsage;

		private global::Gtk.Alignment algnUsage;

		private global::Gtk.VBox pnlDisplays;

		private global::Gtk.VBox pnlNothing;

		private global::Gtk.Label lblNothing;

		private global::Gtk.Label lblRRS;

		private global::Gtk.HBox pnlUsage;

		private global::Gtk.VBox pnlUsageNumbers;

		private global::Gtk.HBox pnlUsageUsed;

		private global::Gtk.Label lblUsageUsed;

		private global::Gtk.Label lblUsageUsedVal;

		private global::Gtk.HBox pnlUsageFree;

		private global::Gtk.Label lblUsageFree;

		private global::Gtk.Label lblUsageFreeVal;

		private global::Gtk.HBox pnlUsageTotal;

		private global::Gtk.Label lblUsageLimit;

		private global::Gtk.Label lblUsageLimitVal;

		private global::Gtk.EventBox evnUsage;

		private global::Gtk.Image pctUsage;

		private global::Gtk.Label lblStatus;

		private global::Gtk.Statusbar sbMainStatus;

		private global::Gtk.ProgressBar pbMainStatus;

		private global::Gtk.Button cmdNetTest;

		private global::Gtk.Label lblMainStatus;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RestrictionTrackerGTK.frmMain
			this.Name = "RestrictionTrackerGTK.frmMain";
			this.Title = global::Mono.Unix.Catalog.GetString("Satellite Restriction Tracker");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("RestrictionTrackerGTK.Resources.norm.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.AllowShrink = true;
			this.Role = "";
			// Container child RestrictionTrackerGTK.frmMain.Gtk.Container+ContainerChild
			this.pnlDetails = new global::Gtk.VBox();
			this.pnlDetails.Name = "pnlDetails";
			// Container child pnlDetails.Gtk.Box+BoxChild
			this.pnlButtons = new global::Gtk.HBox();
			this.pnlButtons.Name = "pnlButtons";
			this.pnlButtons.Homogeneous = true;
			this.pnlButtons.Spacing = 3;
			this.pnlButtons.BorderWidth = ((uint)(3));
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.cmdRefresh = new global::Gtk.Button();
			this.cmdRefresh.TooltipMarkup = "Reload bandwidth level information immediately.\n(Hold CTRL to reload database.)";
			this.cmdRefresh.CanFocus = true;
			this.cmdRefresh.Name = "cmdRefresh";
			this.cmdRefresh.UseUnderline = true;
			this.cmdRefresh.Label = global::Mono.Unix.Catalog.GetString("_Refresh");
			this.pnlButtons.Add(this.cmdRefresh);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.pnlButtons[this.cmdRefresh]));
			w1.Position = 0;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.cmdHistory = new global::Gtk.Button();
			this.cmdHistory.TooltipMarkup = "View your bandwidth history.";
			this.cmdHistory.CanFocus = true;
			this.cmdHistory.Name = "cmdHistory";
			this.cmdHistory.UseUnderline = true;
			this.cmdHistory.Label = global::Mono.Unix.Catalog.GetString("_History");
			this.pnlButtons.Add(this.cmdHistory);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.pnlButtons[this.cmdHistory]));
			w2.Position = 1;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.cmdConfig = new global::Gtk.Button();
			this.cmdConfig.TooltipMarkup = "Change program settings.";
			this.cmdConfig.CanFocus = true;
			this.cmdConfig.Name = "cmdConfig";
			this.cmdConfig.UseUnderline = true;
			this.cmdConfig.Label = global::Mono.Unix.Catalog.GetString("_Configuration");
			this.pnlButtons.Add(this.cmdConfig);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.pnlButtons[this.cmdConfig]));
			w3.Position = 2;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.cmdAbout = new global::Gtk.Button();
			this.cmdAbout.TooltipMarkup = "View information about Satellite Restriction Tracker and check for updates.";
			this.cmdAbout.CanFocus = true;
			this.cmdAbout.Name = "cmdAbout";
			this.cmdAbout.UseUnderline = true;
			this.cmdAbout.Label = global::Mono.Unix.Catalog.GetString("_About");
			this.pnlButtons.Add(this.cmdAbout);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.pnlButtons[this.cmdAbout]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 3;
			this.pnlDetails.Add(this.pnlButtons);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.pnlDetails[this.pnlButtons]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child pnlDetails.Gtk.Box+BoxChild
			this.gbUsage = new global::Gtk.Frame();
			this.gbUsage.Name = "gbUsage";
			this.gbUsage.BorderWidth = ((uint)(3));
			// Container child gbUsage.Gtk.Container+ContainerChild
			this.algnUsage = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.algnUsage.Name = "algnUsage";
			this.algnUsage.LeftPadding = ((uint)(3));
			this.algnUsage.TopPadding = ((uint)(3));
			this.algnUsage.RightPadding = ((uint)(3));
			this.algnUsage.BottomPadding = ((uint)(3));
			// Container child algnUsage.Gtk.Container+ContainerChild
			this.pnlDisplays = new global::Gtk.VBox();
			this.pnlDisplays.Name = "pnlDisplays";
			this.pnlDisplays.Spacing = 6;
			// Container child pnlDisplays.Gtk.Box+BoxChild
			this.pnlNothing = new global::Gtk.VBox();
			this.pnlNothing.Name = "pnlNothing";
			this.pnlNothing.Homogeneous = true;
			this.pnlNothing.Spacing = 6;
			// Container child pnlNothing.Gtk.Box+BoxChild
			this.lblNothing = new global::Gtk.Label();
			this.lblNothing.Name = "lblNothing";
			this.lblNothing.LabelProp = global::Mono.Unix.Catalog.GetString("Satellite Restriction Tracker");
			this.pnlNothing.Add(this.lblNothing);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.pnlNothing[this.lblNothing]));
			w6.Position = 0;
			// Container child pnlNothing.Gtk.Box+BoxChild
			this.lblRRS = new global::Gtk.Label();
			this.lblRRS.CanFocus = true;
			this.lblRRS.Name = "lblRRS";
			this.lblRRS.Xalign = 1F;
			this.lblRRS.LabelProp = global::Mono.Unix.Catalog.GetString("by RealityRipple Software");
			this.pnlNothing.Add(this.lblRRS);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.pnlNothing[this.lblRRS]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.pnlDisplays.Add(this.pnlNothing);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.pnlDisplays[this.pnlNothing]));
			w8.Position = 0;
			// Container child pnlDisplays.Gtk.Box+BoxChild
			this.pnlUsage = new global::Gtk.HBox();
			this.pnlUsage.Name = "pnlUsage";
			this.pnlUsage.Spacing = 6;
			// Container child pnlUsage.Gtk.Box+BoxChild
			this.pnlUsageNumbers = new global::Gtk.VBox();
			this.pnlUsageNumbers.Name = "pnlUsageNumbers";
			this.pnlUsageNumbers.Homogeneous = true;
			this.pnlUsageNumbers.Spacing = 6;
			// Container child pnlUsageNumbers.Gtk.Box+BoxChild
			this.pnlUsageUsed = new global::Gtk.HBox();
			this.pnlUsageUsed.Name = "pnlUsageUsed";
			this.pnlUsageUsed.Spacing = 6;
			// Container child pnlUsageUsed.Gtk.Box+BoxChild
			this.lblUsageUsed = new global::Gtk.Label();
			this.lblUsageUsed.Name = "lblUsageUsed";
			this.lblUsageUsed.LabelProp = global::Mono.Unix.Catalog.GetString("Used:");
			this.pnlUsageUsed.Add(this.lblUsageUsed);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.pnlUsageUsed[this.lblUsageUsed]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child pnlUsageUsed.Gtk.Box+BoxChild
			this.lblUsageUsedVal = new global::Gtk.Label();
			this.lblUsageUsedVal.Name = "lblUsageUsedVal";
			this.lblUsageUsedVal.LabelProp = global::Mono.Unix.Catalog.GetString(" -- ");
			this.pnlUsageUsed.Add(this.lblUsageUsedVal);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.pnlUsageUsed[this.lblUsageUsedVal]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.pnlUsageNumbers.Add(this.pnlUsageUsed);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.pnlUsageNumbers[this.pnlUsageUsed]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child pnlUsageNumbers.Gtk.Box+BoxChild
			this.pnlUsageFree = new global::Gtk.HBox();
			this.pnlUsageFree.Name = "pnlUsageFree";
			this.pnlUsageFree.Spacing = 6;
			// Container child pnlUsageFree.Gtk.Box+BoxChild
			this.lblUsageFree = new global::Gtk.Label();
			this.lblUsageFree.Name = "lblUsageFree";
			this.lblUsageFree.LabelProp = global::Mono.Unix.Catalog.GetString("Free:");
			this.pnlUsageFree.Add(this.lblUsageFree);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.pnlUsageFree[this.lblUsageFree]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child pnlUsageFree.Gtk.Box+BoxChild
			this.lblUsageFreeVal = new global::Gtk.Label();
			this.lblUsageFreeVal.Name = "lblUsageFreeVal";
			this.lblUsageFreeVal.LabelProp = global::Mono.Unix.Catalog.GetString(" -- ");
			this.pnlUsageFree.Add(this.lblUsageFreeVal);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.pnlUsageFree[this.lblUsageFreeVal]));
			w13.PackType = ((global::Gtk.PackType)(1));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.pnlUsageNumbers.Add(this.pnlUsageFree);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.pnlUsageNumbers[this.pnlUsageFree]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child pnlUsageNumbers.Gtk.Box+BoxChild
			this.pnlUsageTotal = new global::Gtk.HBox();
			this.pnlUsageTotal.Name = "pnlUsageTotal";
			this.pnlUsageTotal.Spacing = 6;
			// Container child pnlUsageTotal.Gtk.Box+BoxChild
			this.lblUsageLimit = new global::Gtk.Label();
			this.lblUsageLimit.Name = "lblUsageLimit";
			this.lblUsageLimit.LabelProp = global::Mono.Unix.Catalog.GetString("Limit:");
			this.pnlUsageTotal.Add(this.lblUsageLimit);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.pnlUsageTotal[this.lblUsageLimit]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child pnlUsageTotal.Gtk.Box+BoxChild
			this.lblUsageLimitVal = new global::Gtk.Label();
			this.lblUsageLimitVal.Name = "lblUsageLimitVal";
			this.lblUsageLimitVal.LabelProp = global::Mono.Unix.Catalog.GetString(" -- ");
			this.pnlUsageTotal.Add(this.lblUsageLimitVal);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.pnlUsageTotal[this.lblUsageLimitVal]));
			w16.PackType = ((global::Gtk.PackType)(1));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.pnlUsageNumbers.Add(this.pnlUsageTotal);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.pnlUsageNumbers[this.pnlUsageTotal]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.pnlUsage.Add(this.pnlUsageNumbers);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.pnlUsage[this.pnlUsageNumbers]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child pnlUsage.Gtk.Box+BoxChild
			this.evnUsage = new global::Gtk.EventBox();
			this.evnUsage.Name = "evnUsage";
			// Container child evnUsage.Gtk.Container+ContainerChild
			this.pctUsage = new global::Gtk.Image();
			this.pctUsage.TooltipMarkup = "Graph representing your bandwidth usage.";
			this.pctUsage.Name = "pctUsage";
			this.evnUsage.Add(this.pctUsage);
			this.pnlUsage.Add(this.evnUsage);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.pnlUsage[this.evnUsage]));
			w20.Position = 1;
			this.pnlDisplays.Add(this.pnlUsage);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.pnlDisplays[this.pnlUsage]));
			w21.Position = 1;
			this.algnUsage.Add(this.pnlDisplays);
			this.gbUsage.Add(this.algnUsage);
			this.lblStatus = new global::Gtk.Label();
			this.lblStatus.Name = "lblStatus";
			this.lblStatus.Xalign = 0F;
			this.lblStatus.LabelProp = global::Mono.Unix.Catalog.GetString("Usage Levels");
			this.lblStatus.UseMarkup = true;
			this.gbUsage.LabelWidget = this.lblStatus;
			this.pnlDetails.Add(this.gbUsage);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.pnlDetails[this.gbUsage]));
			w24.Position = 1;
			w24.Padding = ((uint)(3));
			// Container child pnlDetails.Gtk.Box+BoxChild
			this.sbMainStatus = new global::Gtk.Statusbar();
			this.sbMainStatus.Name = "sbMainStatus";
			this.sbMainStatus.Spacing = 6;
			// Container child sbMainStatus.Gtk.Box+BoxChild
			this.pbMainStatus = new global::Gtk.ProgressBar();
			this.pbMainStatus.Name = "pbMainStatus";
			this.sbMainStatus.Add(this.pbMainStatus);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.sbMainStatus[this.pbMainStatus]));
			w25.Position = 1;
			// Container child sbMainStatus.Gtk.Box+BoxChild
			this.cmdNetTest = new global::Gtk.Button();
			this.cmdNetTest.CanFocus = true;
			this.cmdNetTest.Name = "cmdNetTest";
			this.cmdNetTest.UseUnderline = true;
			this.cmdNetTest.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w26 = new global::Gtk.Image();
			this.cmdNetTest.Image = w26;
			this.sbMainStatus.Add(this.cmdNetTest);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.sbMainStatus[this.cmdNetTest]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			// Container child sbMainStatus.Gtk.Box+BoxChild
			this.lblMainStatus = new global::Gtk.Label();
			this.lblMainStatus.Name = "lblMainStatus";
			this.lblMainStatus.SingleLineMode = true;
			this.sbMainStatus.Add(this.lblMainStatus);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.sbMainStatus[this.lblMainStatus]));
			w28.Position = 3;
			w28.Expand = false;
			w28.Fill = false;
			this.pnlDetails.Add(this.sbMainStatus);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.pnlDetails[this.sbMainStatus]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			this.Add(this.pnlDetails);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 455;
			this.DefaultHeight = 302;
			this.Show();
			this.cmdNetTest.Clicked += new global::System.EventHandler(this.cmdNetTest_Clicked);
		}
	}
}
