
// This file has been generated by the GUI designer. Do not modify.
namespace RestrictionTrackerGTK
{
	public partial class dlgUpdate
	{
		private global::Gtk.VBox pnlUpdate;
		private global::Gtk.Label lblNewVer;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView txtInfo;
		private global::Gtk.Label lblBETA;
		private global::Gtk.CheckButton chkStopBETA;
		private global::Gtk.Button cmdDownload;
		private global::Gtk.Button cmdCancel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RestrictionTrackerGTK.dlgUpdate
			this.Name = "RestrictionTrackerGTK.dlgUpdate";
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("RestrictionTrackerGTK.Resources.norm.ico");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			this.AllowGrow = false;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Internal child RestrictionTrackerGTK.dlgUpdate.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "pnlUpdateDialog";
			w1.BorderWidth = ((uint)(2));
			// Container child pnlUpdateDialog.Gtk.Box+BoxChild
			this.pnlUpdate = new global::Gtk.VBox ();
			this.pnlUpdate.Name = "pnlUpdate";
			this.pnlUpdate.Spacing = 6;
			// Container child pnlUpdate.Gtk.Box+BoxChild
			this.lblNewVer = new global::Gtk.Label ();
			this.lblNewVer.Name = "lblNewVer";
			this.lblNewVer.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size=\"12000\">Satellite Restriction Tracker Update\nVersion 0.0.0.0</span>");
			this.lblNewVer.UseMarkup = true;
			this.lblNewVer.Justify = ((global::Gtk.Justification)(2));
			this.pnlUpdate.Add (this.lblNewVer);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.pnlUpdate [this.lblNewVer]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child pnlUpdate.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtInfo = new global::Gtk.TextView ();
			this.txtInfo.CanFocus = true;
			this.txtInfo.Name = "txtInfo";
			this.txtInfo.Editable = false;
			this.txtInfo.AcceptsTab = false;
			this.txtInfo.WrapMode = ((global::Gtk.WrapMode)(3));
			this.GtkScrolledWindow.Add (this.txtInfo);
			this.pnlUpdate.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.pnlUpdate [this.GtkScrolledWindow]));
			w4.Position = 1;
			// Container child pnlUpdate.Gtk.Box+BoxChild
			this.lblBETA = new global::Gtk.Label ();
			this.lblBETA.Name = "lblBETA";
			this.lblBETA.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"Firebrick\">BETA updates may have bugs and other issues that haven't been worked out yet, but need testing on a wide range of accounts.\nPlease back up your history before using BETAs.</span>");
			this.lblBETA.UseMarkup = true;
			this.lblBETA.Wrap = true;
			this.pnlUpdate.Add (this.lblBETA);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.pnlUpdate [this.lblBETA]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child pnlUpdate.Gtk.Box+BoxChild
			this.chkStopBETA = new global::Gtk.CheckButton ();
			this.chkStopBETA.CanFocus = true;
			this.chkStopBETA.Name = "chkStopBETA";
			this.chkStopBETA.Label = global::Mono.Unix.Catalog.GetString ("Don't notify me of BETA updates.");
			this.chkStopBETA.DrawIndicator = true;
			this.chkStopBETA.UseUnderline = true;
			this.pnlUpdate.Add (this.chkStopBETA);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.pnlUpdate [this.chkStopBETA]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			w1.Add (this.pnlUpdate);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1 [this.pnlUpdate]));
			w7.Position = 0;
			// Internal child RestrictionTrackerGTK.dlgUpdate.ActionArea
			global::Gtk.HButtonBox w8 = this.ActionArea;
			w8.Name = "pnlUpdateButtons";
			w8.Homogeneous = true;
			w8.Spacing = 10;
			w8.BorderWidth = ((uint)(5));
			w8.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child pnlUpdateButtons.Gtk.ButtonBox+ButtonBoxChild
			this.cmdDownload = new global::Gtk.Button ();
			this.cmdDownload.CanDefault = true;
			this.cmdDownload.CanFocus = true;
			this.cmdDownload.Name = "cmdDownload";
			this.cmdDownload.UseUnderline = true;
			// Container child cmdDownload.Gtk.Container+ContainerChild
			global::Gtk.Alignment w9 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w10 = new global::Gtk.HBox ();
			w10.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w11 = new global::Gtk.Image ();
			w11.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("RestrictionTrackerGTK.Resources.web.png");
			w10.Add (w11);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w13 = new global::Gtk.Label ();
			w13.LabelProp = global::Mono.Unix.Catalog.GetString ("Visit _Website");
			w13.UseUnderline = true;
			w10.Add (w13);
			w9.Add (w10);
			this.cmdDownload.Add (w9);
			this.AddActionWidget (this.cmdDownload, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.cmdDownload]));
			w17.Expand = false;
			w17.Fill = false;
			// Container child pnlUpdateButtons.Gtk.ButtonBox+ButtonBoxChild
			this.cmdCancel = new global::Gtk.Button ();
			this.cmdCancel.CanDefault = true;
			this.cmdCancel.CanFocus = true;
			this.cmdCancel.Name = "cmdCancel";
			this.cmdCancel.UseUnderline = true;
			// Container child cmdCancel.Gtk.Container+ContainerChild
			global::Gtk.Alignment w18 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w19 = new global::Gtk.HBox ();
			w19.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w20 = new global::Gtk.Image ();
			w20.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Button);
			w19.Add (w20);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w22 = new global::Gtk.Label ();
			w22.LabelProp = global::Mono.Unix.Catalog.GetString ("_Not Now");
			w22.UseUnderline = true;
			w19.Add (w22);
			w18.Add (w19);
			this.cmdCancel.Add (w18);
			this.AddActionWidget (this.cmdCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w26 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.cmdCancel]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 324;
			this.DefaultHeight = 415;
			this.Hide ();
			this.cmdDownload.Clicked += new global::System.EventHandler (this.cmdDownload_Click);
			this.cmdCancel.Clicked += new global::System.EventHandler (this.cmdCancel_Click);
		}
	}
}
