
// This file has been generated by the GUI designer. Do not modify.
namespace RestrictionTrackerGTK
{
	public partial class frmHistory
	{
		private global::Gtk.VBox pnlHistory;
		private global::Gtk.Frame grpAge;
		private global::Gtk.Alignment algnAge;
		private global::Gtk.Table pnlAge;
		private global::Gtk.Alignment algnFrom;
		private global::Gtk.Alignment algnTo;
		private global::Gtk.Button cmd30Days;
		private global::Gtk.Button cmd60Days;
		private global::Gtk.Button cmdAllTime;
		private global::Gtk.Button cmdQuery;
		private global::Gtk.Button cmdToday;
		private global::Gtk.Label lblFrom;
		private global::Gtk.Label lblTo;
		private global::Gtk.RadioButton optGraph;
		private global::Gtk.RadioButton optGrid;
		private global::Gtk.Image pctErr;
		private global::Gtk.Label GtkLabel8;
		private global::Gtk.VBox pnlGraph;
		private global::Gtk.EventBox evnDld;
		private global::Gtk.Image pctDld;
		private global::Gtk.EventBox evnUld;
		private global::Gtk.Image pctUld;
		private global::Gtk.HBox pnlButtons;
		private global::Gtk.Label lblBackup;
		private global::Gtk.Button cmdImport;
		private global::Gtk.Button cmdExport;
		private global::Gtk.Button cmdClose;
		private global::Gtk.CheckButton chkExportRange;
		private global::Gtk.Statusbar sbHistoryStatus;
		private global::Gtk.ProgressBar pbHistoryStatus;
		private global::Gtk.Label lblHistoryStatus;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RestrictionTrackerGTK.frmHistory
			this.Name = "RestrictionTrackerGTK.frmHistory";
			this.Title = global::Mono.Unix.Catalog.GetString ("Satellite Restriction Tracker Usage History");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("RestrictionTrackerGTK.Resources.norm.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(3));
			// Container child RestrictionTrackerGTK.frmHistory.Gtk.Container+ContainerChild
			this.pnlHistory = new global::Gtk.VBox ();
			this.pnlHistory.Name = "pnlHistory";
			this.pnlHistory.Spacing = 6;
			// Container child pnlHistory.Gtk.Box+BoxChild
			this.grpAge = new global::Gtk.Frame ();
			this.grpAge.Name = "grpAge";
			this.grpAge.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child grpAge.Gtk.Container+ContainerChild
			this.algnAge = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.algnAge.Name = "algnAge";
			this.algnAge.LeftPadding = ((uint)(3));
			this.algnAge.TopPadding = ((uint)(3));
			this.algnAge.RightPadding = ((uint)(3));
			this.algnAge.BottomPadding = ((uint)(3));
			// Container child algnAge.Gtk.Container+ContainerChild
			this.pnlAge = new global::Gtk.Table (((uint)(2)), ((uint)(6)), false);
			this.pnlAge.Name = "pnlAge";
			this.pnlAge.RowSpacing = ((uint)(6));
			this.pnlAge.ColumnSpacing = ((uint)(6));
			// Container child pnlAge.Gtk.Table+TableChild
			this.algnFrom = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.algnFrom.Name = "algnFrom";
			this.pnlAge.Add (this.algnFrom);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.pnlAge [this.algnFrom]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child pnlAge.Gtk.Table+TableChild
			this.algnTo = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.algnTo.Name = "algnTo";
			this.pnlAge.Add (this.algnTo);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.pnlAge [this.algnTo]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child pnlAge.Gtk.Table+TableChild
			this.cmd30Days = new global::Gtk.Button ();
			this.cmd30Days.TooltipMarkup = "Query the database to get the last 30 days' history.";
			this.cmd30Days.CanFocus = true;
			this.cmd30Days.Name = "cmd30Days";
			this.cmd30Days.UseUnderline = true;
			this.cmd30Days.Xalign = 0F;
			// Container child cmd30Days.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("RestrictionTrackerGTK.Resources.cal30.png");
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w7.LabelProp = global::Mono.Unix.Catalog.GetString ("30 Days");
			w7.UseUnderline = true;
			w4.Add (w7);
			w3.Add (w4);
			this.cmd30Days.Add (w3);
			this.pnlAge.Add (this.cmd30Days);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.pnlAge [this.cmd30Days]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(4));
			w11.RightAttach = ((uint)(5));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.cmd60Days = new global::Gtk.Button ();
			this.cmd60Days.TooltipMarkup = "Query the database to get the last 60 days' history.";
			this.cmd60Days.CanFocus = true;
			this.cmd60Days.Name = "cmd60Days";
			this.cmd60Days.UseUnderline = true;
			this.cmd60Days.Xalign = 0F;
			// Container child cmd60Days.Gtk.Container+ContainerChild
			global::Gtk.Alignment w12 = new global::Gtk.Alignment (0F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w13 = new global::Gtk.HBox ();
			w13.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("RestrictionTrackerGTK.Resources.cal60.png");
			w13.Add (w14);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w16 = new global::Gtk.Label ();
			w16.LabelProp = global::Mono.Unix.Catalog.GetString ("60 Days");
			w16.UseUnderline = true;
			w13.Add (w16);
			w12.Add (w13);
			this.cmd60Days.Add (w12);
			this.pnlAge.Add (this.cmd60Days);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.pnlAge [this.cmd60Days]));
			w20.LeftAttach = ((uint)(5));
			w20.RightAttach = ((uint)(6));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.cmdAllTime = new global::Gtk.Button ();
			this.cmdAllTime.TooltipMarkup = "Query the database to get the entire history.";
			this.cmdAllTime.CanFocus = true;
			this.cmdAllTime.Name = "cmdAllTime";
			this.cmdAllTime.UseUnderline = true;
			this.cmdAllTime.Xalign = 0F;
			// Container child cmdAllTime.Gtk.Container+ContainerChild
			global::Gtk.Alignment w21 = new global::Gtk.Alignment (0F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w22 = new global::Gtk.HBox ();
			w22.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w23 = new global::Gtk.Image ();
			w23.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("RestrictionTrackerGTK.Resources.calall.png");
			w22.Add (w23);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w25 = new global::Gtk.Label ();
			w25.LabelProp = global::Mono.Unix.Catalog.GetString ("All Time");
			w25.UseUnderline = true;
			w22.Add (w25);
			w21.Add (w22);
			this.cmdAllTime.Add (w21);
			this.pnlAge.Add (this.cmdAllTime);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.pnlAge [this.cmdAllTime]));
			w29.TopAttach = ((uint)(1));
			w29.BottomAttach = ((uint)(2));
			w29.LeftAttach = ((uint)(5));
			w29.RightAttach = ((uint)(6));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.cmdQuery = new global::Gtk.Button ();
			this.cmdQuery.TooltipMarkup = "Query the database to get your requested history.";
			this.cmdQuery.CanFocus = true;
			this.cmdQuery.Name = "cmdQuery";
			this.cmdQuery.UseUnderline = true;
			// Container child cmdQuery.Gtk.Container+ContainerChild
			global::Gtk.Alignment w30 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w31 = new global::Gtk.HBox ();
			w31.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w32 = new global::Gtk.Image ();
			w32.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Button);
			w31.Add (w32);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w34 = new global::Gtk.Label ();
			w34.LabelProp = global::Mono.Unix.Catalog.GetString ("Query");
			w34.UseUnderline = true;
			w31.Add (w34);
			w30.Add (w31);
			this.cmdQuery.Add (w30);
			this.pnlAge.Add (this.cmdQuery);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.pnlAge [this.cmdQuery]));
			w38.LeftAttach = ((uint)(3));
			w38.RightAttach = ((uint)(4));
			w38.XOptions = ((global::Gtk.AttachOptions)(4));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.cmdToday = new global::Gtk.Button ();
			this.cmdToday.TooltipMarkup = "Query the database to get today's history.";
			this.cmdToday.CanFocus = true;
			this.cmdToday.Name = "cmdToday";
			this.cmdToday.UseUnderline = true;
			this.cmdToday.Xalign = 0F;
			// Container child cmdToday.Gtk.Container+ContainerChild
			global::Gtk.Alignment w39 = new global::Gtk.Alignment (0F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w40 = new global::Gtk.HBox ();
			w40.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w41 = new global::Gtk.Image ();
			w41.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("RestrictionTrackerGTK.Resources.cal1.png");
			w40.Add (w41);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w43 = new global::Gtk.Label ();
			w43.LabelProp = global::Mono.Unix.Catalog.GetString ("Today");
			w43.UseUnderline = true;
			w40.Add (w43);
			w39.Add (w40);
			this.cmdToday.Add (w39);
			this.pnlAge.Add (this.cmdToday);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.pnlAge [this.cmdToday]));
			w47.LeftAttach = ((uint)(4));
			w47.RightAttach = ((uint)(5));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.lblFrom = new global::Gtk.Label ();
			this.lblFrom.Name = "lblFrom";
			this.lblFrom.Xalign = 0F;
			this.lblFrom.LabelProp = global::Mono.Unix.Catalog.GetString ("From:");
			this.pnlAge.Add (this.lblFrom);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.pnlAge [this.lblFrom]));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.lblTo = new global::Gtk.Label ();
			this.lblTo.Name = "lblTo";
			this.lblTo.Xalign = 0F;
			this.lblTo.LabelProp = global::Mono.Unix.Catalog.GetString ("To:");
			this.pnlAge.Add (this.lblTo);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.pnlAge [this.lblTo]));
			w49.TopAttach = ((uint)(1));
			w49.BottomAttach = ((uint)(2));
			w49.XOptions = ((global::Gtk.AttachOptions)(4));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.optGraph = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Graph"));
			this.optGraph.TooltipMarkup = "Display history in a line graph.";
			this.optGraph.CanFocus = true;
			this.optGraph.Name = "optGraph";
			this.optGraph.Active = true;
			this.optGraph.DrawIndicator = true;
			this.optGraph.UseUnderline = true;
			this.optGraph.Yalign = 0F;
			this.optGraph.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.pnlAge.Add (this.optGraph);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.pnlAge [this.optGraph]));
			w50.LeftAttach = ((uint)(2));
			w50.RightAttach = ((uint)(3));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.optGrid = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Grid"));
			this.optGrid.TooltipMarkup = "Display history in a grid.";
			this.optGrid.CanFocus = true;
			this.optGrid.Name = "optGrid";
			this.optGrid.DrawIndicator = true;
			this.optGrid.UseUnderline = true;
			this.optGrid.Yalign = 0F;
			this.optGrid.Group = this.optGraph.Group;
			this.pnlAge.Add (this.optGrid);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.pnlAge [this.optGrid]));
			w51.TopAttach = ((uint)(1));
			w51.BottomAttach = ((uint)(2));
			w51.LeftAttach = ((uint)(2));
			w51.RightAttach = ((uint)(3));
			w51.XOptions = ((global::Gtk.AttachOptions)(4));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.pctErr = new global::Gtk.Image ();
			this.pctErr.WidthRequest = 16;
			this.pctErr.HeightRequest = 16;
			this.pctErr.Name = "pctErr";
			this.pnlAge.Add (this.pctErr);
			global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.pnlAge [this.pctErr]));
			w52.TopAttach = ((uint)(1));
			w52.BottomAttach = ((uint)(2));
			w52.LeftAttach = ((uint)(3));
			w52.RightAttach = ((uint)(4));
			w52.XOptions = ((global::Gtk.AttachOptions)(0));
			w52.YOptions = ((global::Gtk.AttachOptions)(0));
			this.algnAge.Add (this.pnlAge);
			this.grpAge.Add (this.algnAge);
			this.GtkLabel8 = new global::Gtk.Label ();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.Xalign = 0F;
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("Age Parameters");
			this.GtkLabel8.UseMarkup = true;
			this.grpAge.LabelWidget = this.GtkLabel8;
			this.pnlHistory.Add (this.grpAge);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.pnlHistory [this.grpAge]));
			w55.Position = 0;
			w55.Expand = false;
			w55.Fill = false;
			// Container child pnlHistory.Gtk.Box+BoxChild
			this.pnlGraph = new global::Gtk.VBox ();
			this.pnlGraph.Name = "pnlGraph";
			this.pnlGraph.Homogeneous = true;
			this.pnlGraph.Spacing = 6;
			// Container child pnlGraph.Gtk.Box+BoxChild
			this.evnDld = new global::Gtk.EventBox ();
			this.evnDld.Name = "evnDld";
			// Container child evnDld.Gtk.Container+ContainerChild
			this.pctDld = new global::Gtk.Image ();
			this.pctDld.Name = "pctDld";
			this.evnDld.Add (this.pctDld);
			this.pnlGraph.Add (this.evnDld);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.pnlGraph [this.evnDld]));
			w57.Position = 0;
			// Container child pnlGraph.Gtk.Box+BoxChild
			this.evnUld = new global::Gtk.EventBox ();
			this.evnUld.Name = "evnUld";
			// Container child evnUld.Gtk.Container+ContainerChild
			this.pctUld = new global::Gtk.Image ();
			this.pctUld.Name = "pctUld";
			this.evnUld.Add (this.pctUld);
			this.pnlGraph.Add (this.evnUld);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.pnlGraph [this.evnUld]));
			w59.Position = 1;
			this.pnlHistory.Add (this.pnlGraph);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.pnlHistory [this.pnlGraph]));
			w60.Position = 1;
			// Container child pnlHistory.Gtk.Box+BoxChild
			this.pnlButtons = new global::Gtk.HBox ();
			this.pnlButtons.Name = "pnlButtons";
			this.pnlButtons.Spacing = 6;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.lblBackup = new global::Gtk.Label ();
			this.lblBackup.Name = "lblBackup";
			this.lblBackup.LabelProp = global::Mono.Unix.Catalog.GetString ("Backup:");
			this.pnlButtons.Add (this.lblBackup);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.pnlButtons [this.lblBackup]));
			w61.Position = 0;
			w61.Expand = false;
			w61.Fill = false;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.cmdImport = new global::Gtk.Button ();
			this.cmdImport.TooltipMarkup = "Read a DataBase, XML, or CSV file into the history.";
			this.cmdImport.CanFocus = true;
			this.cmdImport.Name = "cmdImport";
			this.cmdImport.UseUnderline = true;
			// Container child cmdImport.Gtk.Container+ContainerChild
			global::Gtk.Alignment w62 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w63 = new global::Gtk.HBox ();
			w63.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w64 = new global::Gtk.Image ();
			w64.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Button);
			w63.Add (w64);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w66 = new global::Gtk.Label ();
			w66.LabelProp = global::Mono.Unix.Catalog.GetString ("Import Database");
			w66.UseUnderline = true;
			w63.Add (w66);
			w62.Add (w63);
			this.cmdImport.Add (w62);
			this.pnlButtons.Add (this.cmdImport);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.pnlButtons [this.cmdImport]));
			w70.Position = 1;
			w70.Expand = false;
			w70.Fill = false;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.cmdExport = new global::Gtk.Button ();
			this.cmdExport.TooltipMarkup = "Make a backup DataBase, XML, or CSV file.";
			this.cmdExport.CanFocus = true;
			this.cmdExport.Name = "cmdExport";
			this.cmdExport.UseUnderline = true;
			// Container child cmdExport.Gtk.Container+ContainerChild
			global::Gtk.Alignment w71 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w72 = new global::Gtk.HBox ();
			w72.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w73 = new global::Gtk.Image ();
			w73.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save-as", global::Gtk.IconSize.Button);
			w72.Add (w73);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w75 = new global::Gtk.Label ();
			w75.LabelProp = global::Mono.Unix.Catalog.GetString ("Export Database");
			w75.UseUnderline = true;
			w72.Add (w75);
			w71.Add (w72);
			this.cmdExport.Add (w71);
			this.pnlButtons.Add (this.cmdExport);
			global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.pnlButtons [this.cmdExport]));
			w79.Position = 2;
			w79.Expand = false;
			w79.Fill = false;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.cmdClose = new global::Gtk.Button ();
			this.cmdClose.TooltipMarkup = "Close the History window.";
			this.cmdClose.CanFocus = true;
			this.cmdClose.Name = "cmdClose";
			this.cmdClose.UseUnderline = true;
			// Container child cmdClose.Gtk.Container+ContainerChild
			global::Gtk.Alignment w80 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w81 = new global::Gtk.HBox ();
			w81.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w82 = new global::Gtk.Image ();
			w82.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Button);
			w81.Add (w82);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w84 = new global::Gtk.Label ();
			w84.LabelProp = global::Mono.Unix.Catalog.GetString ("_Close");
			w84.UseUnderline = true;
			w81.Add (w84);
			w80.Add (w81);
			this.cmdClose.Add (w80);
			this.pnlButtons.Add (this.cmdClose);
			global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.pnlButtons [this.cmdClose]));
			w88.PackType = ((global::Gtk.PackType)(1));
			w88.Position = 3;
			w88.Expand = false;
			w88.Fill = false;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.chkExportRange = new global::Gtk.CheckButton ();
			this.chkExportRange.TooltipMarkup = "Export only the data within the Age Parameters range.";
			this.chkExportRange.CanFocus = true;
			this.chkExportRange.Name = "chkExportRange";
			this.chkExportRange.Label = global::Mono.Unix.Catalog.GetString ("Export Selected Range");
			this.chkExportRange.DrawIndicator = true;
			this.chkExportRange.UseUnderline = true;
			this.pnlButtons.Add (this.chkExportRange);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.pnlButtons [this.chkExportRange]));
			w89.PackType = ((global::Gtk.PackType)(1));
			w89.Position = 4;
			this.pnlHistory.Add (this.pnlButtons);
			global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.pnlHistory [this.pnlButtons]));
			w90.Position = 2;
			w90.Expand = false;
			w90.Fill = false;
			// Container child pnlHistory.Gtk.Box+BoxChild
			this.sbHistoryStatus = new global::Gtk.Statusbar ();
			this.sbHistoryStatus.Name = "sbHistoryStatus";
			this.sbHistoryStatus.Spacing = 2;
			// Container child sbHistoryStatus.Gtk.Box+BoxChild
			this.pbHistoryStatus = new global::Gtk.ProgressBar ();
			this.pbHistoryStatus.Name = "pbHistoryStatus";
			this.sbHistoryStatus.Add (this.pbHistoryStatus);
			global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.sbHistoryStatus [this.pbHistoryStatus]));
			w91.Position = 1;
			// Container child sbHistoryStatus.Gtk.Box+BoxChild
			this.lblHistoryStatus = new global::Gtk.Label ();
			this.lblHistoryStatus.Name = "lblHistoryStatus";
			this.lblHistoryStatus.Xalign = 0F;
			this.lblHistoryStatus.SingleLineMode = true;
			this.sbHistoryStatus.Add (this.lblHistoryStatus);
			global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.sbHistoryStatus [this.lblHistoryStatus]));
			w92.Position = 2;
			w92.Expand = false;
			w92.Fill = false;
			this.pnlHistory.Add (this.sbHistoryStatus);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.pnlHistory [this.sbHistoryStatus]));
			w93.Position = 3;
			w93.Expand = false;
			w93.Fill = false;
			this.Add (this.pnlHistory);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 571;
			this.DefaultHeight = 356;
			this.Show ();
			this.cmdToday.Clicked += new global::System.EventHandler (this.cmdToday_Click);
			this.cmdQuery.Clicked += new global::System.EventHandler (this.cmdQuery_Click);
			this.cmdAllTime.Clicked += new global::System.EventHandler (this.cmdAllTime_Click);
			this.cmd60Days.Clicked += new global::System.EventHandler (this.cmd60Days_Click);
			this.cmd30Days.Clicked += new global::System.EventHandler (this.cmd30Days_Click);
			this.cmdImport.Clicked += new global::System.EventHandler (this.cmdImport_Click);
			this.cmdExport.Clicked += new global::System.EventHandler (this.cmdExport_Click);
			this.cmdClose.Clicked += new global::System.EventHandler (this.cmdClose_Click);
		}
	}
}
