
// This file has been generated by the GUI designer. Do not modify.
namespace RestrictionTrackerGTK
{
	public partial class frmHistory
	{
		private global::Gtk.VBox pnlHistory;

		private global::Gtk.Frame grpAge;

		private global::Gtk.Alignment algnAge;

		private global::Gtk.Table pnlAge;

		private global::Gtk.Alignment algnFrom;

		private global::Gtk.Alignment algnTo;

		private global::Gtk.Button cmd30Days;

		private global::Gtk.Button cmd60Days;

		private global::Gtk.Button cmdAllTime;

		private global::Gtk.Button cmdQuery;

		private global::Gtk.Button cmdToday;

		private global::Gtk.Label lblFrom;

		private global::Gtk.Label lblTo;

		private global::Gtk.RadioButton optGraph;

		private global::Gtk.RadioButton optGrid;

		private global::Gtk.Image pctErr;

		private global::Gtk.Label lblAgeTitle;

		private global::Gtk.EventBox evnGraph;

		private global::Gtk.Image pctGraph;

		private global::Gtk.HBox pnlButtons;

		private global::Gtk.Label lblBackup;

		private global::Gtk.Button cmdImport;

		private global::Gtk.Button cmdExport;

		private global::Gtk.Button cmdClose;

		private global::Gtk.CheckButton chkExportRange;

		private global::Gtk.Statusbar sbHistoryStatus;

		private global::Gtk.ProgressBar pbHistoryStatus;

		private global::Gtk.Label lblHistoryStatus;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RestrictionTrackerGTK.frmHistory
			this.Name = "RestrictionTrackerGTK.frmHistory";
			this.Title = global::Mono.Unix.Catalog.GetString("Satellite Restriction Tracker Usage History");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("RestrictionTrackerGTK.Resources.norm.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(3));
			// Container child RestrictionTrackerGTK.frmHistory.Gtk.Container+ContainerChild
			this.pnlHistory = new global::Gtk.VBox();
			this.pnlHistory.Name = "pnlHistory";
			this.pnlHistory.Spacing = 6;
			// Container child pnlHistory.Gtk.Box+BoxChild
			this.grpAge = new global::Gtk.Frame();
			this.grpAge.Name = "grpAge";
			this.grpAge.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child grpAge.Gtk.Container+ContainerChild
			this.algnAge = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.algnAge.Name = "algnAge";
			this.algnAge.LeftPadding = ((uint)(3));
			this.algnAge.TopPadding = ((uint)(3));
			this.algnAge.RightPadding = ((uint)(3));
			this.algnAge.BottomPadding = ((uint)(3));
			// Container child algnAge.Gtk.Container+ContainerChild
			this.pnlAge = new global::Gtk.Table(((uint)(2)), ((uint)(6)), false);
			this.pnlAge.Name = "pnlAge";
			this.pnlAge.RowSpacing = ((uint)(6));
			this.pnlAge.ColumnSpacing = ((uint)(6));
			// Container child pnlAge.Gtk.Table+TableChild
			this.algnFrom = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.algnFrom.Name = "algnFrom";
			this.pnlAge.Add(this.algnFrom);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.pnlAge[this.algnFrom]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child pnlAge.Gtk.Table+TableChild
			this.algnTo = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.algnTo.Name = "algnTo";
			this.pnlAge.Add(this.algnTo);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.pnlAge[this.algnTo]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child pnlAge.Gtk.Table+TableChild
			this.cmd30Days = new global::Gtk.Button();
			this.cmd30Days.TooltipMarkup = "Query the database to get the history of the last 30 days.";
			this.cmd30Days.CanFocus = true;
			this.cmd30Days.Name = "cmd30Days";
			this.cmd30Days.UseUnderline = true;
			this.cmd30Days.Label = global::Mono.Unix.Catalog.GetString("30 Days");
			this.pnlAge.Add(this.cmd30Days);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.pnlAge[this.cmd30Days]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(4));
			w3.RightAttach = ((uint)(5));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.cmd60Days = new global::Gtk.Button();
			this.cmd60Days.TooltipMarkup = "Query the database to get the history of the last 60 days.";
			this.cmd60Days.CanFocus = true;
			this.cmd60Days.Name = "cmd60Days";
			this.cmd60Days.UseUnderline = true;
			this.cmd60Days.Label = global::Mono.Unix.Catalog.GetString("60 Days");
			this.pnlAge.Add(this.cmd60Days);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.pnlAge[this.cmd60Days]));
			w4.LeftAttach = ((uint)(5));
			w4.RightAttach = ((uint)(6));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.cmdAllTime = new global::Gtk.Button();
			this.cmdAllTime.TooltipMarkup = "Query the database to get the entire history.";
			this.cmdAllTime.CanFocus = true;
			this.cmdAllTime.Name = "cmdAllTime";
			this.cmdAllTime.UseUnderline = true;
			this.cmdAllTime.Label = global::Mono.Unix.Catalog.GetString("_All Time");
			this.pnlAge.Add(this.cmdAllTime);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.pnlAge[this.cmdAllTime]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(5));
			w5.RightAttach = ((uint)(6));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.cmdQuery = new global::Gtk.Button();
			this.cmdQuery.TooltipMarkup = "Query the database to get your requested history.";
			this.cmdQuery.CanFocus = true;
			this.cmdQuery.Name = "cmdQuery";
			this.cmdQuery.UseUnderline = true;
			this.cmdQuery.Label = global::Mono.Unix.Catalog.GetString("_Query");
			this.pnlAge.Add(this.cmdQuery);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.pnlAge[this.cmdQuery]));
			w6.LeftAttach = ((uint)(3));
			w6.RightAttach = ((uint)(4));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.cmdToday = new global::Gtk.Button();
			this.cmdToday.TooltipMarkup = "Query the database to get today\'s history.";
			this.cmdToday.CanFocus = true;
			this.cmdToday.Name = "cmdToday";
			this.cmdToday.UseUnderline = true;
			this.cmdToday.Label = global::Mono.Unix.Catalog.GetString("T_oday");
			this.pnlAge.Add(this.cmdToday);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.pnlAge[this.cmdToday]));
			w7.LeftAttach = ((uint)(4));
			w7.RightAttach = ((uint)(5));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.lblFrom = new global::Gtk.Label();
			this.lblFrom.Name = "lblFrom";
			this.lblFrom.Xalign = 0F;
			this.lblFrom.LabelProp = global::Mono.Unix.Catalog.GetString("_From:");
			this.lblFrom.UseUnderline = true;
			this.pnlAge.Add(this.lblFrom);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.pnlAge[this.lblFrom]));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.lblTo = new global::Gtk.Label();
			this.lblTo.Name = "lblTo";
			this.lblTo.Xalign = 0F;
			this.lblTo.LabelProp = global::Mono.Unix.Catalog.GetString("_To:");
			this.lblTo.UseUnderline = true;
			this.pnlAge.Add(this.lblTo);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.pnlAge[this.lblTo]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.optGraph = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("_Graph"));
			this.optGraph.TooltipMarkup = "Display history in a line graph.";
			this.optGraph.CanFocus = true;
			this.optGraph.Name = "optGraph";
			this.optGraph.DrawIndicator = true;
			this.optGraph.UseUnderline = true;
			this.optGraph.Yalign = 0F;
			this.optGraph.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.pnlAge.Add(this.optGraph);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.pnlAge[this.optGraph]));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.optGrid = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Gri_d"));
			this.optGrid.TooltipMarkup = "Display history in a grid.";
			this.optGrid.CanFocus = true;
			this.optGrid.Name = "optGrid";
			this.optGrid.DrawIndicator = true;
			this.optGrid.UseUnderline = true;
			this.optGrid.Yalign = 0F;
			this.optGrid.Group = this.optGraph.Group;
			this.pnlAge.Add(this.optGrid);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.pnlAge[this.optGrid]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(2));
			w11.RightAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlAge.Gtk.Table+TableChild
			this.pctErr = new global::Gtk.Image();
			this.pctErr.WidthRequest = 16;
			this.pctErr.HeightRequest = 16;
			this.pctErr.Name = "pctErr";
			this.pnlAge.Add(this.pctErr);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.pnlAge[this.pctErr]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(3));
			w12.RightAttach = ((uint)(4));
			w12.XOptions = ((global::Gtk.AttachOptions)(0));
			w12.YOptions = ((global::Gtk.AttachOptions)(0));
			this.algnAge.Add(this.pnlAge);
			this.grpAge.Add(this.algnAge);
			this.lblAgeTitle = new global::Gtk.Label();
			this.lblAgeTitle.Name = "lblAgeTitle";
			this.lblAgeTitle.Xalign = 0F;
			this.lblAgeTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Age Parameters");
			this.lblAgeTitle.UseMarkup = true;
			this.grpAge.LabelWidget = this.lblAgeTitle;
			this.pnlHistory.Add(this.grpAge);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.pnlHistory[this.grpAge]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child pnlHistory.Gtk.Box+BoxChild
			this.evnGraph = new global::Gtk.EventBox();
			this.evnGraph.Name = "evnGraph";
			// Container child evnGraph.Gtk.Container+ContainerChild
			this.pctGraph = new global::Gtk.Image();
			this.pctGraph.Name = "pctGraph";
			this.evnGraph.Add(this.pctGraph);
			this.pnlHistory.Add(this.evnGraph);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.pnlHistory[this.evnGraph]));
			w17.Position = 1;
			// Container child pnlHistory.Gtk.Box+BoxChild
			this.pnlButtons = new global::Gtk.HBox();
			this.pnlButtons.Name = "pnlButtons";
			this.pnlButtons.Spacing = 6;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.lblBackup = new global::Gtk.Label();
			this.lblBackup.Name = "lblBackup";
			this.lblBackup.LabelProp = global::Mono.Unix.Catalog.GetString("Backup:");
			this.pnlButtons.Add(this.lblBackup);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.pnlButtons[this.lblBackup]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.cmdImport = new global::Gtk.Button();
			this.cmdImport.TooltipMarkup = "Read a DataBase, XML, or CSV file into the history.";
			this.cmdImport.CanFocus = true;
			this.cmdImport.Name = "cmdImport";
			this.cmdImport.UseUnderline = true;
			this.cmdImport.Label = global::Mono.Unix.Catalog.GetString("_Import Database");
			this.pnlButtons.Add(this.cmdImport);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.pnlButtons[this.cmdImport]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.cmdExport = new global::Gtk.Button();
			this.cmdExport.TooltipMarkup = "Make a backup DataBase, XML, or CSV file.";
			this.cmdExport.CanFocus = true;
			this.cmdExport.Name = "cmdExport";
			this.cmdExport.UseUnderline = true;
			this.cmdExport.Label = global::Mono.Unix.Catalog.GetString("_Export Database");
			this.pnlButtons.Add(this.cmdExport);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.pnlButtons[this.cmdExport]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.cmdClose = new global::Gtk.Button();
			this.cmdClose.TooltipMarkup = "Close the History window.";
			this.cmdClose.CanFocus = true;
			this.cmdClose.Name = "cmdClose";
			this.cmdClose.UseUnderline = true;
			this.cmdClose.Label = global::Mono.Unix.Catalog.GetString("Close");
			this.pnlButtons.Add(this.cmdClose);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.pnlButtons[this.cmdClose]));
			w21.PackType = ((global::Gtk.PackType)(1));
			w21.Position = 3;
			w21.Expand = false;
			w21.Fill = false;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.chkExportRange = new global::Gtk.CheckButton();
			this.chkExportRange.TooltipMarkup = "Export only the data within the Age Parameters range.";
			this.chkExportRange.CanFocus = true;
			this.chkExportRange.Name = "chkExportRange";
			this.chkExportRange.Label = global::Mono.Unix.Catalog.GetString("Export Selected _Range");
			this.chkExportRange.DrawIndicator = true;
			this.chkExportRange.UseUnderline = true;
			this.pnlButtons.Add(this.chkExportRange);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.pnlButtons[this.chkExportRange]));
			w22.PackType = ((global::Gtk.PackType)(1));
			w22.Position = 4;
			this.pnlHistory.Add(this.pnlButtons);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.pnlHistory[this.pnlButtons]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			// Container child pnlHistory.Gtk.Box+BoxChild
			this.sbHistoryStatus = new global::Gtk.Statusbar();
			this.sbHistoryStatus.Name = "sbHistoryStatus";
			this.sbHistoryStatus.Spacing = 2;
			// Container child sbHistoryStatus.Gtk.Box+BoxChild
			this.pbHistoryStatus = new global::Gtk.ProgressBar();
			this.pbHistoryStatus.Name = "pbHistoryStatus";
			this.sbHistoryStatus.Add(this.pbHistoryStatus);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.sbHistoryStatus[this.pbHistoryStatus]));
			w24.Position = 1;
			// Container child sbHistoryStatus.Gtk.Box+BoxChild
			this.lblHistoryStatus = new global::Gtk.Label();
			this.lblHistoryStatus.Name = "lblHistoryStatus";
			this.lblHistoryStatus.Xalign = 0F;
			this.lblHistoryStatus.SingleLineMode = true;
			this.sbHistoryStatus.Add(this.lblHistoryStatus);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.sbHistoryStatus[this.lblHistoryStatus]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			this.pnlHistory.Add(this.sbHistoryStatus);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.pnlHistory[this.sbHistoryStatus]));
			w26.Position = 3;
			w26.Expand = false;
			w26.Fill = false;
			this.Add(this.pnlHistory);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 583;
			this.DefaultHeight = 399;
			this.Show();
		}
	}
}
