
// This file has been generated by the GUI designer. Do not modify.
namespace RestrictionTrackerGTK
{
	public partial class dlgCustomColors
	{
		private global::Gtk.Table pnlCustomColors;
		private global::Gtk.Frame grpHistory;
		private global::Gtk.Alignment algnHistory;
		private global::Gtk.Table pnlHistory;
		private global::Gtk.EventBox evnHistory;
		private global::Gtk.Image pctHistory;
		private global::Gtk.Frame grpHistoryDown;
		private global::Gtk.Alignment algnHistoryDown;
		private global::Gtk.Table pnlHistoryDown;
		private global::Gtk.CheckButton chkHistoryDownB;
		private global::Gtk.ColorButton cmdHistoryDownA;
		private global::Gtk.ColorButton cmdHistoryDownB;
		private global::Gtk.ColorButton cmdHistoryDownC;
		private global::Gtk.ColorButton cmdHistoryDownMax;
		private global::Gtk.Label lblHistoryDownA;
		private global::Gtk.Label lblHistoryDownC;
		private global::Gtk.Label lblHistoryDownMax;
		private global::Gtk.Label lblHistoryDownTitle;
		private global::Gtk.Frame grpHistoryUp;
		private global::Gtk.Alignment algnHistoryUp;
		private global::Gtk.Table pnlHistoryUp;
		private global::Gtk.CheckButton chkHistoryUpB;
		private global::Gtk.ColorButton cmdHistoryUpA;
		private global::Gtk.ColorButton cmdHistoryUpB;
		private global::Gtk.ColorButton cmdHistoryUpC;
		private global::Gtk.ColorButton cmdHistoryUpMax;
		private global::Gtk.Label lblHistoryUpA;
		private global::Gtk.Label lblHistoryUpC;
		private global::Gtk.Label lblHistoryUpMax;
		private global::Gtk.Label lblHistoryUpTitle;
		private global::Gtk.Table pnlHistoryStyle;
		private global::Gtk.ColorButton cmdHistoryBG;
		private global::Gtk.ColorButton cmdHistoryText;
		private global::Gtk.Label lblHistoryBG;
		private global::Gtk.Label lblHistoryText;
		private global::Gtk.Label lblHistoryTitle;
		private global::Gtk.Frame grpMain;
		private global::Gtk.Alignment algnMain;
		private global::Gtk.Table pnlMain;
		private global::Gtk.EventBox evnMain;
		private global::Gtk.Image pctMain;
		private global::Gtk.Frame grpMainDown;
		private global::Gtk.Alignment algnMainDown;
		private global::Gtk.Table pnlMainDown;
		private global::Gtk.CheckButton chkMainDownB;
		private global::Gtk.ColorButton cmdMainDownA;
		private global::Gtk.ColorButton cmdMainDownB;
		private global::Gtk.ColorButton cmdMainDownC;
		private global::Gtk.Label lblMainDownA;
		private global::Gtk.Label lblMainDownC;
		private global::Gtk.Label lblMainDownTitle;
		private global::Gtk.Frame grpMainUp;
		private global::Gtk.Alignment algnMainUp;
		private global::Gtk.Table pnlMainUp;
		private global::Gtk.CheckButton chkMainUpB;
		private global::Gtk.ColorButton cmdMainUpA;
		private global::Gtk.ColorButton cmdMainUpB;
		private global::Gtk.ColorButton cmdMainUpC;
		private global::Gtk.Label lblMainUpA;
		private global::Gtk.Label lblMainUpC;
		private global::Gtk.Label lblMainUpTitle;
		private global::Gtk.Table pnlMainStyle;
		private global::Gtk.ColorButton cmdMainBG;
		private global::Gtk.ColorButton cmdMainText;
		private global::Gtk.Label lblMainBG;
		private global::Gtk.Label lblMainText;
		private global::Gtk.Label lblMainTitle;
		private global::Gtk.Frame grpTray;
		private global::Gtk.Alignment algnTray;
		private global::Gtk.Table pnlTray;
		private global::Gtk.EventBox evnTray;
		private global::Gtk.Image pctTray;
		private global::Gtk.Frame grpTrayDown;
		private global::Gtk.Alignment algnTrayDown;
		private global::Gtk.Table pnlTrayDown;
		private global::Gtk.CheckButton chkTrayDownB;
		private global::Gtk.ColorButton cmdTrayDownA;
		private global::Gtk.ColorButton cmdTrayDownB;
		private global::Gtk.ColorButton cmdTrayDownC;
		private global::Gtk.Label lblTrayDownA;
		private global::Gtk.Label lblTrayDownC;
		private global::Gtk.Label lblTrayDownTitle;
		private global::Gtk.Frame grpTrayUp;
		private global::Gtk.Alignment algnTrayUp;
		private global::Gtk.Table pnlTrayUp;
		private global::Gtk.CheckButton chkTrayUpB;
		private global::Gtk.ColorButton cmdTrayUpA;
		private global::Gtk.ColorButton cmdTrayUpB;
		private global::Gtk.ColorButton cmdTrayUpC;
		private global::Gtk.Label lblTrayUpA;
		private global::Gtk.Label lblTrayUpC;
		private global::Gtk.Label lblTrayUpTitle;
		private global::Gtk.Label lblTrayTitle;
		private global::Gtk.Button cmdSave;
		private global::Gtk.Button cmdClose;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RestrictionTrackerGTK.dlgCustomColors
			this.Name = "RestrictionTrackerGTK.dlgCustomColors";
			this.Title = global::Mono.Unix.Catalog.GetString ("Graph Color Customization");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("RestrictionTrackerGTK.Resources.norm.ico");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			this.AllowGrow = false;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Internal child RestrictionTrackerGTK.dlgCustomColors.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "pnlColors";
			w1.BorderWidth = ((uint)(2));
			// Container child pnlColors.Gtk.Box+BoxChild
			this.pnlCustomColors = new global::Gtk.Table (((uint)(3)), ((uint)(1)), false);
			this.pnlCustomColors.Name = "pnlCustomColors";
			this.pnlCustomColors.RowSpacing = ((uint)(3));
			this.pnlCustomColors.ColumnSpacing = ((uint)(3));
			// Container child pnlCustomColors.Gtk.Table+TableChild
			this.grpHistory = new global::Gtk.Frame ();
			this.grpHistory.Name = "grpHistory";
			// Container child grpHistory.Gtk.Container+ContainerChild
			this.algnHistory = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.algnHistory.Name = "algnHistory";
			this.algnHistory.LeftPadding = ((uint)(3));
			this.algnHistory.TopPadding = ((uint)(3));
			this.algnHistory.RightPadding = ((uint)(3));
			this.algnHistory.BottomPadding = ((uint)(3));
			// Container child algnHistory.Gtk.Container+ContainerChild
			this.pnlHistory = new global::Gtk.Table (((uint)(2)), ((uint)(3)), false);
			this.pnlHistory.Name = "pnlHistory";
			this.pnlHistory.RowSpacing = ((uint)(3));
			this.pnlHistory.ColumnSpacing = ((uint)(3));
			// Container child pnlHistory.Gtk.Table+TableChild
			this.evnHistory = new global::Gtk.EventBox ();
			this.evnHistory.Name = "evnHistory";
			// Container child evnHistory.Gtk.Container+ContainerChild
			this.pctHistory = new global::Gtk.Image ();
			this.pctHistory.WidthRequest = 75;
			this.pctHistory.HeightRequest = 75;
			this.pctHistory.Name = "pctHistory";
			this.evnHistory.Add (this.pctHistory);
			this.pnlHistory.Add (this.evnHistory);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.pnlHistory [this.evnHistory]));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistory.Gtk.Table+TableChild
			this.grpHistoryDown = new global::Gtk.Frame ();
			this.grpHistoryDown.Name = "grpHistoryDown";
			this.grpHistoryDown.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child grpHistoryDown.Gtk.Container+ContainerChild
			this.algnHistoryDown = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.algnHistoryDown.Name = "algnHistoryDown";
			this.algnHistoryDown.LeftPadding = ((uint)(3));
			this.algnHistoryDown.TopPadding = ((uint)(3));
			this.algnHistoryDown.RightPadding = ((uint)(3));
			this.algnHistoryDown.BottomPadding = ((uint)(3));
			// Container child algnHistoryDown.Gtk.Container+ContainerChild
			this.pnlHistoryDown = new global::Gtk.Table (((uint)(4)), ((uint)(3)), false);
			this.pnlHistoryDown.Name = "pnlHistoryDown";
			this.pnlHistoryDown.RowSpacing = ((uint)(3));
			this.pnlHistoryDown.ColumnSpacing = ((uint)(3));
			// Container child pnlHistoryDown.Gtk.Table+TableChild
			this.chkHistoryDownB = new global::Gtk.CheckButton ();
			this.chkHistoryDownB.CanFocus = true;
			this.chkHistoryDownB.Name = "chkHistoryDownB";
			this.chkHistoryDownB.Label = global::Mono.Unix.Catalog.GetString ("50% :");
			this.chkHistoryDownB.DrawIndicator = true;
			this.chkHistoryDownB.UseUnderline = true;
			this.pnlHistoryDown.Add (this.chkHistoryDownB);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.pnlHistoryDown [this.chkHistoryDownB]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(0));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryDown.Gtk.Table+TableChild
			this.cmdHistoryDownA = new global::Gtk.ColorButton ();
			this.cmdHistoryDownA.CanFocus = true;
			this.cmdHistoryDownA.Events = ((global::Gdk.EventMask)(784));
			this.cmdHistoryDownA.Name = "cmdHistoryDownA";
			this.cmdHistoryDownA.Title = global::Mono.Unix.Catalog.GetString ("History Graph Download 0% Color");
			this.pnlHistoryDown.Add (this.cmdHistoryDownA);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.pnlHistoryDown [this.cmdHistoryDownA]));
			w5.LeftAttach = ((uint)(2));
			w5.RightAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryDown.Gtk.Table+TableChild
			this.cmdHistoryDownB = new global::Gtk.ColorButton ();
			this.cmdHistoryDownB.CanFocus = true;
			this.cmdHistoryDownB.Events = ((global::Gdk.EventMask)(784));
			this.cmdHistoryDownB.Name = "cmdHistoryDownB";
			this.cmdHistoryDownB.Title = global::Mono.Unix.Catalog.GetString ("History Graph Download 50% Color");
			this.pnlHistoryDown.Add (this.cmdHistoryDownB);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.pnlHistoryDown [this.cmdHistoryDownB]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryDown.Gtk.Table+TableChild
			this.cmdHistoryDownC = new global::Gtk.ColorButton ();
			this.cmdHistoryDownC.CanFocus = true;
			this.cmdHistoryDownC.Events = ((global::Gdk.EventMask)(784));
			this.cmdHistoryDownC.Name = "cmdHistoryDownC";
			this.cmdHistoryDownC.Title = global::Mono.Unix.Catalog.GetString ("History Graph Download 100% Color");
			this.pnlHistoryDown.Add (this.cmdHistoryDownC);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.pnlHistoryDown [this.cmdHistoryDownC]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryDown.Gtk.Table+TableChild
			this.cmdHistoryDownMax = new global::Gtk.ColorButton ();
			this.cmdHistoryDownMax.CanFocus = true;
			this.cmdHistoryDownMax.Events = ((global::Gdk.EventMask)(784));
			this.cmdHistoryDownMax.Name = "cmdHistoryDownMax";
			this.cmdHistoryDownMax.Title = global::Mono.Unix.Catalog.GetString ("History Graph Download Maximum Limit Color");
			this.pnlHistoryDown.Add (this.cmdHistoryDownMax);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.pnlHistoryDown [this.cmdHistoryDownMax]));
			w8.TopAttach = ((uint)(3));
			w8.BottomAttach = ((uint)(4));
			w8.LeftAttach = ((uint)(2));
			w8.RightAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryDown.Gtk.Table+TableChild
			this.lblHistoryDownA = new global::Gtk.Label ();
			this.lblHistoryDownA.Name = "lblHistoryDownA";
			this.lblHistoryDownA.Xalign = 1F;
			this.lblHistoryDownA.LabelProp = global::Mono.Unix.Catalog.GetString ("0% :");
			this.pnlHistoryDown.Add (this.lblHistoryDownA);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.pnlHistoryDown [this.lblHistoryDownA]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryDown.Gtk.Table+TableChild
			this.lblHistoryDownC = new global::Gtk.Label ();
			this.lblHistoryDownC.Name = "lblHistoryDownC";
			this.lblHistoryDownC.Xalign = 1F;
			this.lblHistoryDownC.LabelProp = global::Mono.Unix.Catalog.GetString ("100% :");
			this.pnlHistoryDown.Add (this.lblHistoryDownC);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.pnlHistoryDown [this.lblHistoryDownC]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryDown.Gtk.Table+TableChild
			this.lblHistoryDownMax = new global::Gtk.Label ();
			this.lblHistoryDownMax.Name = "lblHistoryDownMax";
			this.lblHistoryDownMax.Xalign = 1F;
			this.lblHistoryDownMax.LabelProp = global::Mono.Unix.Catalog.GetString ("Max");
			this.pnlHistoryDown.Add (this.lblHistoryDownMax);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.pnlHistoryDown [this.lblHistoryDownMax]));
			w11.TopAttach = ((uint)(3));
			w11.BottomAttach = ((uint)(4));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			this.algnHistoryDown.Add (this.pnlHistoryDown);
			this.grpHistoryDown.Add (this.algnHistoryDown);
			this.lblHistoryDownTitle = new global::Gtk.Label ();
			this.lblHistoryDownTitle.Name = "lblHistoryDownTitle";
			this.lblHistoryDownTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Download Colors");
			this.lblHistoryDownTitle.UseMarkup = true;
			this.grpHistoryDown.LabelWidget = this.lblHistoryDownTitle;
			this.pnlHistory.Add (this.grpHistoryDown);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.pnlHistory [this.grpHistoryDown]));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistory.Gtk.Table+TableChild
			this.grpHistoryUp = new global::Gtk.Frame ();
			this.grpHistoryUp.Name = "grpHistoryUp";
			this.grpHistoryUp.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child grpHistoryUp.Gtk.Container+ContainerChild
			this.algnHistoryUp = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.algnHistoryUp.Name = "algnHistoryUp";
			this.algnHistoryUp.LeftPadding = ((uint)(3));
			this.algnHistoryUp.TopPadding = ((uint)(3));
			this.algnHistoryUp.RightPadding = ((uint)(3));
			this.algnHistoryUp.BottomPadding = ((uint)(3));
			// Container child algnHistoryUp.Gtk.Container+ContainerChild
			this.pnlHistoryUp = new global::Gtk.Table (((uint)(4)), ((uint)(3)), false);
			this.pnlHistoryUp.Name = "pnlHistoryUp";
			this.pnlHistoryUp.RowSpacing = ((uint)(3));
			this.pnlHistoryUp.ColumnSpacing = ((uint)(3));
			// Container child pnlHistoryUp.Gtk.Table+TableChild
			this.chkHistoryUpB = new global::Gtk.CheckButton ();
			this.chkHistoryUpB.CanFocus = true;
			this.chkHistoryUpB.Name = "chkHistoryUpB";
			this.chkHistoryUpB.Label = global::Mono.Unix.Catalog.GetString ("50% :");
			this.chkHistoryUpB.DrawIndicator = true;
			this.chkHistoryUpB.UseUnderline = true;
			this.pnlHistoryUp.Add (this.chkHistoryUpB);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.pnlHistoryUp [this.chkHistoryUpB]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(0));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryUp.Gtk.Table+TableChild
			this.cmdHistoryUpA = new global::Gtk.ColorButton ();
			this.cmdHistoryUpA.CanFocus = true;
			this.cmdHistoryUpA.Events = ((global::Gdk.EventMask)(784));
			this.cmdHistoryUpA.Name = "cmdHistoryUpA";
			this.cmdHistoryUpA.Title = global::Mono.Unix.Catalog.GetString ("History Graph Upload 0% Color");
			this.pnlHistoryUp.Add (this.cmdHistoryUpA);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.pnlHistoryUp [this.cmdHistoryUpA]));
			w16.LeftAttach = ((uint)(2));
			w16.RightAttach = ((uint)(3));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryUp.Gtk.Table+TableChild
			this.cmdHistoryUpB = new global::Gtk.ColorButton ();
			this.cmdHistoryUpB.CanFocus = true;
			this.cmdHistoryUpB.Events = ((global::Gdk.EventMask)(784));
			this.cmdHistoryUpB.Name = "cmdHistoryUpB";
			this.cmdHistoryUpB.Title = global::Mono.Unix.Catalog.GetString ("History Graph Upload 50% Color");
			this.pnlHistoryUp.Add (this.cmdHistoryUpB);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.pnlHistoryUp [this.cmdHistoryUpB]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.LeftAttach = ((uint)(2));
			w17.RightAttach = ((uint)(3));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryUp.Gtk.Table+TableChild
			this.cmdHistoryUpC = new global::Gtk.ColorButton ();
			this.cmdHistoryUpC.CanFocus = true;
			this.cmdHistoryUpC.Events = ((global::Gdk.EventMask)(784));
			this.cmdHistoryUpC.Name = "cmdHistoryUpC";
			this.cmdHistoryUpC.Title = global::Mono.Unix.Catalog.GetString ("History Graph Upload 100% Color");
			this.pnlHistoryUp.Add (this.cmdHistoryUpC);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.pnlHistoryUp [this.cmdHistoryUpC]));
			w18.TopAttach = ((uint)(2));
			w18.BottomAttach = ((uint)(3));
			w18.LeftAttach = ((uint)(2));
			w18.RightAttach = ((uint)(3));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryUp.Gtk.Table+TableChild
			this.cmdHistoryUpMax = new global::Gtk.ColorButton ();
			this.cmdHistoryUpMax.CanFocus = true;
			this.cmdHistoryUpMax.Events = ((global::Gdk.EventMask)(784));
			this.cmdHistoryUpMax.Name = "cmdHistoryUpMax";
			this.cmdHistoryUpMax.Title = global::Mono.Unix.Catalog.GetString ("History Graph Upload Maximum Limit Color");
			this.pnlHistoryUp.Add (this.cmdHistoryUpMax);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.pnlHistoryUp [this.cmdHistoryUpMax]));
			w19.TopAttach = ((uint)(3));
			w19.BottomAttach = ((uint)(4));
			w19.LeftAttach = ((uint)(2));
			w19.RightAttach = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryUp.Gtk.Table+TableChild
			this.lblHistoryUpA = new global::Gtk.Label ();
			this.lblHistoryUpA.Name = "lblHistoryUpA";
			this.lblHistoryUpA.Xalign = 1F;
			this.lblHistoryUpA.LabelProp = global::Mono.Unix.Catalog.GetString ("0% :");
			this.pnlHistoryUp.Add (this.lblHistoryUpA);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.pnlHistoryUp [this.lblHistoryUpA]));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryUp.Gtk.Table+TableChild
			this.lblHistoryUpC = new global::Gtk.Label ();
			this.lblHistoryUpC.Name = "lblHistoryUpC";
			this.lblHistoryUpC.Xalign = 1F;
			this.lblHistoryUpC.LabelProp = global::Mono.Unix.Catalog.GetString ("100% :");
			this.pnlHistoryUp.Add (this.lblHistoryUpC);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.pnlHistoryUp [this.lblHistoryUpC]));
			w21.TopAttach = ((uint)(2));
			w21.BottomAttach = ((uint)(3));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryUp.Gtk.Table+TableChild
			this.lblHistoryUpMax = new global::Gtk.Label ();
			this.lblHistoryUpMax.Name = "lblHistoryUpMax";
			this.lblHistoryUpMax.Xalign = 1F;
			this.lblHistoryUpMax.LabelProp = global::Mono.Unix.Catalog.GetString ("Max:");
			this.pnlHistoryUp.Add (this.lblHistoryUpMax);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.pnlHistoryUp [this.lblHistoryUpMax]));
			w22.TopAttach = ((uint)(3));
			w22.BottomAttach = ((uint)(4));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			this.algnHistoryUp.Add (this.pnlHistoryUp);
			this.grpHistoryUp.Add (this.algnHistoryUp);
			this.lblHistoryUpTitle = new global::Gtk.Label ();
			this.lblHistoryUpTitle.Name = "lblHistoryUpTitle";
			this.lblHistoryUpTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Upload Colors");
			this.lblHistoryUpTitle.UseMarkup = true;
			this.grpHistoryUp.LabelWidget = this.lblHistoryUpTitle;
			this.pnlHistory.Add (this.grpHistoryUp);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.pnlHistory [this.grpHistoryUp]));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistory.Gtk.Table+TableChild
			this.pnlHistoryStyle = new global::Gtk.Table (((uint)(1)), ((uint)(5)), false);
			this.pnlHistoryStyle.Name = "pnlHistoryStyle";
			this.pnlHistoryStyle.RowSpacing = ((uint)(3));
			this.pnlHistoryStyle.ColumnSpacing = ((uint)(3));
			// Container child pnlHistoryStyle.Gtk.Table+TableChild
			this.cmdHistoryBG = new global::Gtk.ColorButton ();
			this.cmdHistoryBG.CanFocus = true;
			this.cmdHistoryBG.Events = ((global::Gdk.EventMask)(784));
			this.cmdHistoryBG.Name = "cmdHistoryBG";
			this.pnlHistoryStyle.Add (this.cmdHistoryBG);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.pnlHistoryStyle [this.cmdHistoryBG]));
			w26.LeftAttach = ((uint)(4));
			w26.RightAttach = ((uint)(5));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryStyle.Gtk.Table+TableChild
			this.cmdHistoryText = new global::Gtk.ColorButton ();
			this.cmdHistoryText.CanFocus = true;
			this.cmdHistoryText.Events = ((global::Gdk.EventMask)(784));
			this.cmdHistoryText.Name = "cmdHistoryText";
			this.cmdHistoryText.Title = global::Mono.Unix.Catalog.GetString ("History Graph Upload Text Color");
			this.pnlHistoryStyle.Add (this.cmdHistoryText);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.pnlHistoryStyle [this.cmdHistoryText]));
			w27.LeftAttach = ((uint)(1));
			w27.RightAttach = ((uint)(2));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryStyle.Gtk.Table+TableChild
			this.lblHistoryBG = new global::Gtk.Label ();
			this.lblHistoryBG.Name = "lblHistoryBG";
			this.lblHistoryBG.Xalign = 0F;
			this.lblHistoryBG.LabelProp = global::Mono.Unix.Catalog.GetString ("Background:");
			this.pnlHistoryStyle.Add (this.lblHistoryBG);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.pnlHistoryStyle [this.lblHistoryBG]));
			w28.LeftAttach = ((uint)(3));
			w28.RightAttach = ((uint)(4));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHistoryStyle.Gtk.Table+TableChild
			this.lblHistoryText = new global::Gtk.Label ();
			this.lblHistoryText.Name = "lblHistoryText";
			this.lblHistoryText.Xalign = 0F;
			this.lblHistoryText.LabelProp = global::Mono.Unix.Catalog.GetString ("Text Color:");
			this.pnlHistoryStyle.Add (this.lblHistoryText);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.pnlHistoryStyle [this.lblHistoryText]));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			this.pnlHistory.Add (this.pnlHistoryStyle);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.pnlHistory [this.pnlHistoryStyle]));
			w30.TopAttach = ((uint)(1));
			w30.BottomAttach = ((uint)(2));
			w30.RightAttach = ((uint)(2));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			this.algnHistory.Add (this.pnlHistory);
			this.grpHistory.Add (this.algnHistory);
			this.lblHistoryTitle = new global::Gtk.Label ();
			this.lblHistoryTitle.Name = "lblHistoryTitle";
			this.lblHistoryTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("History Window Graphs");
			this.lblHistoryTitle.UseMarkup = true;
			this.grpHistory.LabelWidget = this.lblHistoryTitle;
			this.pnlCustomColors.Add (this.grpHistory);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.pnlCustomColors [this.grpHistory]));
			w33.TopAttach = ((uint)(2));
			w33.BottomAttach = ((uint)(3));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlCustomColors.Gtk.Table+TableChild
			this.grpMain = new global::Gtk.Frame ();
			this.grpMain.Name = "grpMain";
			// Container child grpMain.Gtk.Container+ContainerChild
			this.algnMain = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.algnMain.Name = "algnMain";
			this.algnMain.LeftPadding = ((uint)(3));
			this.algnMain.TopPadding = ((uint)(3));
			this.algnMain.RightPadding = ((uint)(3));
			this.algnMain.BottomPadding = ((uint)(3));
			// Container child algnMain.Gtk.Container+ContainerChild
			this.pnlMain = new global::Gtk.Table (((uint)(2)), ((uint)(3)), false);
			this.pnlMain.Name = "pnlMain";
			this.pnlMain.RowSpacing = ((uint)(3));
			this.pnlMain.ColumnSpacing = ((uint)(3));
			// Container child pnlMain.Gtk.Table+TableChild
			this.evnMain = new global::Gtk.EventBox ();
			this.evnMain.Name = "evnMain";
			// Container child evnMain.Gtk.Container+ContainerChild
			this.pctMain = new global::Gtk.Image ();
			this.pctMain.WidthRequest = 75;
			this.pctMain.HeightRequest = 75;
			this.pctMain.Name = "pctMain";
			this.evnMain.Add (this.pctMain);
			this.pnlMain.Add (this.evnMain);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.pnlMain [this.evnMain]));
			w35.BottomAttach = ((uint)(2));
			w35.LeftAttach = ((uint)(2));
			w35.RightAttach = ((uint)(3));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlMain.Gtk.Table+TableChild
			this.grpMainDown = new global::Gtk.Frame ();
			this.grpMainDown.Name = "grpMainDown";
			this.grpMainDown.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child grpMainDown.Gtk.Container+ContainerChild
			this.algnMainDown = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.algnMainDown.Name = "algnMainDown";
			this.algnMainDown.LeftPadding = ((uint)(3));
			this.algnMainDown.TopPadding = ((uint)(3));
			this.algnMainDown.RightPadding = ((uint)(3));
			this.algnMainDown.BottomPadding = ((uint)(3));
			// Container child algnMainDown.Gtk.Container+ContainerChild
			this.pnlMainDown = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.pnlMainDown.Name = "pnlMainDown";
			this.pnlMainDown.RowSpacing = ((uint)(3));
			this.pnlMainDown.ColumnSpacing = ((uint)(3));
			// Container child pnlMainDown.Gtk.Table+TableChild
			this.chkMainDownB = new global::Gtk.CheckButton ();
			this.chkMainDownB.CanFocus = true;
			this.chkMainDownB.Name = "chkMainDownB";
			this.chkMainDownB.Label = global::Mono.Unix.Catalog.GetString ("50% :");
			this.chkMainDownB.DrawIndicator = true;
			this.chkMainDownB.UseUnderline = true;
			this.pnlMainDown.Add (this.chkMainDownB);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.pnlMainDown [this.chkMainDownB]));
			w36.TopAttach = ((uint)(1));
			w36.BottomAttach = ((uint)(2));
			w36.XOptions = ((global::Gtk.AttachOptions)(0));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlMainDown.Gtk.Table+TableChild
			this.cmdMainDownA = new global::Gtk.ColorButton ();
			this.cmdMainDownA.CanFocus = true;
			this.cmdMainDownA.Events = ((global::Gdk.EventMask)(784));
			this.cmdMainDownA.Name = "cmdMainDownA";
			this.cmdMainDownA.Title = global::Mono.Unix.Catalog.GetString ("Main Graph Download 0% Color");
			this.pnlMainDown.Add (this.cmdMainDownA);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.pnlMainDown [this.cmdMainDownA]));
			w37.LeftAttach = ((uint)(2));
			w37.RightAttach = ((uint)(3));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlMainDown.Gtk.Table+TableChild
			this.cmdMainDownB = new global::Gtk.ColorButton ();
			this.cmdMainDownB.CanFocus = true;
			this.cmdMainDownB.Events = ((global::Gdk.EventMask)(784));
			this.cmdMainDownB.Name = "cmdMainDownB";
			this.cmdMainDownB.Title = global::Mono.Unix.Catalog.GetString ("Main Graph Download 50% Color");
			this.pnlMainDown.Add (this.cmdMainDownB);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.pnlMainDown [this.cmdMainDownB]));
			w38.TopAttach = ((uint)(1));
			w38.BottomAttach = ((uint)(2));
			w38.LeftAttach = ((uint)(2));
			w38.RightAttach = ((uint)(3));
			w38.XOptions = ((global::Gtk.AttachOptions)(4));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlMainDown.Gtk.Table+TableChild
			this.cmdMainDownC = new global::Gtk.ColorButton ();
			this.cmdMainDownC.CanFocus = true;
			this.cmdMainDownC.Events = ((global::Gdk.EventMask)(784));
			this.cmdMainDownC.Name = "cmdMainDownC";
			this.cmdMainDownC.Title = global::Mono.Unix.Catalog.GetString ("Main Graph Download 100% Color");
			this.pnlMainDown.Add (this.cmdMainDownC);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.pnlMainDown [this.cmdMainDownC]));
			w39.TopAttach = ((uint)(2));
			w39.BottomAttach = ((uint)(3));
			w39.LeftAttach = ((uint)(2));
			w39.RightAttach = ((uint)(3));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlMainDown.Gtk.Table+TableChild
			this.lblMainDownA = new global::Gtk.Label ();
			this.lblMainDownA.Name = "lblMainDownA";
			this.lblMainDownA.Xalign = 1F;
			this.lblMainDownA.LabelProp = global::Mono.Unix.Catalog.GetString ("0% :");
			this.pnlMainDown.Add (this.lblMainDownA);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.pnlMainDown [this.lblMainDownA]));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlMainDown.Gtk.Table+TableChild
			this.lblMainDownC = new global::Gtk.Label ();
			this.lblMainDownC.Name = "lblMainDownC";
			this.lblMainDownC.Xalign = 1F;
			this.lblMainDownC.LabelProp = global::Mono.Unix.Catalog.GetString ("100% :");
			this.pnlMainDown.Add (this.lblMainDownC);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.pnlMainDown [this.lblMainDownC]));
			w41.TopAttach = ((uint)(2));
			w41.BottomAttach = ((uint)(3));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			this.algnMainDown.Add (this.pnlMainDown);
			this.grpMainDown.Add (this.algnMainDown);
			this.lblMainDownTitle = new global::Gtk.Label ();
			this.lblMainDownTitle.Name = "lblMainDownTitle";
			this.lblMainDownTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Download Colors");
			this.lblMainDownTitle.UseMarkup = true;
			this.grpMainDown.LabelWidget = this.lblMainDownTitle;
			this.pnlMain.Add (this.grpMainDown);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.pnlMain [this.grpMainDown]));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlMain.Gtk.Table+TableChild
			this.grpMainUp = new global::Gtk.Frame ();
			this.grpMainUp.Name = "grpMainUp";
			this.grpMainUp.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child grpMainUp.Gtk.Container+ContainerChild
			this.algnMainUp = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.algnMainUp.Name = "algnMainUp";
			this.algnMainUp.LeftPadding = ((uint)(3));
			this.algnMainUp.TopPadding = ((uint)(3));
			this.algnMainUp.RightPadding = ((uint)(3));
			this.algnMainUp.BottomPadding = ((uint)(3));
			// Container child algnMainUp.Gtk.Container+ContainerChild
			this.pnlMainUp = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.pnlMainUp.Name = "pnlMainUp";
			this.pnlMainUp.RowSpacing = ((uint)(3));
			this.pnlMainUp.ColumnSpacing = ((uint)(3));
			// Container child pnlMainUp.Gtk.Table+TableChild
			this.chkMainUpB = new global::Gtk.CheckButton ();
			this.chkMainUpB.CanFocus = true;
			this.chkMainUpB.Name = "chkMainUpB";
			this.chkMainUpB.Label = global::Mono.Unix.Catalog.GetString ("50% :");
			this.chkMainUpB.DrawIndicator = true;
			this.chkMainUpB.UseUnderline = true;
			this.pnlMainUp.Add (this.chkMainUpB);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.pnlMainUp [this.chkMainUpB]));
			w45.TopAttach = ((uint)(1));
			w45.BottomAttach = ((uint)(2));
			w45.XOptions = ((global::Gtk.AttachOptions)(0));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlMainUp.Gtk.Table+TableChild
			this.cmdMainUpA = new global::Gtk.ColorButton ();
			this.cmdMainUpA.CanFocus = true;
			this.cmdMainUpA.Events = ((global::Gdk.EventMask)(784));
			this.cmdMainUpA.Name = "cmdMainUpA";
			this.cmdMainUpA.Title = global::Mono.Unix.Catalog.GetString ("Main Graph Upload 0% Color");
			this.pnlMainUp.Add (this.cmdMainUpA);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.pnlMainUp [this.cmdMainUpA]));
			w46.LeftAttach = ((uint)(2));
			w46.RightAttach = ((uint)(3));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlMainUp.Gtk.Table+TableChild
			this.cmdMainUpB = new global::Gtk.ColorButton ();
			this.cmdMainUpB.CanFocus = true;
			this.cmdMainUpB.Events = ((global::Gdk.EventMask)(784));
			this.cmdMainUpB.Name = "cmdMainUpB";
			this.cmdMainUpB.Title = global::Mono.Unix.Catalog.GetString ("Main Graph Upload 50% Color");
			this.pnlMainUp.Add (this.cmdMainUpB);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.pnlMainUp [this.cmdMainUpB]));
			w47.TopAttach = ((uint)(1));
			w47.BottomAttach = ((uint)(2));
			w47.LeftAttach = ((uint)(2));
			w47.RightAttach = ((uint)(3));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlMainUp.Gtk.Table+TableChild
			this.cmdMainUpC = new global::Gtk.ColorButton ();
			this.cmdMainUpC.CanFocus = true;
			this.cmdMainUpC.Events = ((global::Gdk.EventMask)(784));
			this.cmdMainUpC.Name = "cmdMainUpC";
			this.cmdMainUpC.Title = global::Mono.Unix.Catalog.GetString ("Main Graph Upload 100% Color");
			this.pnlMainUp.Add (this.cmdMainUpC);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.pnlMainUp [this.cmdMainUpC]));
			w48.TopAttach = ((uint)(2));
			w48.BottomAttach = ((uint)(3));
			w48.LeftAttach = ((uint)(2));
			w48.RightAttach = ((uint)(3));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlMainUp.Gtk.Table+TableChild
			this.lblMainUpA = new global::Gtk.Label ();
			this.lblMainUpA.Name = "lblMainUpA";
			this.lblMainUpA.Xalign = 1F;
			this.lblMainUpA.LabelProp = global::Mono.Unix.Catalog.GetString ("0% :");
			this.pnlMainUp.Add (this.lblMainUpA);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.pnlMainUp [this.lblMainUpA]));
			w49.XOptions = ((global::Gtk.AttachOptions)(4));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlMainUp.Gtk.Table+TableChild
			this.lblMainUpC = new global::Gtk.Label ();
			this.lblMainUpC.Name = "lblMainUpC";
			this.lblMainUpC.Xalign = 1F;
			this.lblMainUpC.LabelProp = global::Mono.Unix.Catalog.GetString ("100% :");
			this.pnlMainUp.Add (this.lblMainUpC);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.pnlMainUp [this.lblMainUpC]));
			w50.TopAttach = ((uint)(2));
			w50.BottomAttach = ((uint)(3));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			this.algnMainUp.Add (this.pnlMainUp);
			this.grpMainUp.Add (this.algnMainUp);
			this.lblMainUpTitle = new global::Gtk.Label ();
			this.lblMainUpTitle.Name = "lblMainUpTitle";
			this.lblMainUpTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Upload Colors");
			this.lblMainUpTitle.UseMarkup = true;
			this.grpMainUp.LabelWidget = this.lblMainUpTitle;
			this.pnlMain.Add (this.grpMainUp);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.pnlMain [this.grpMainUp]));
			w53.LeftAttach = ((uint)(1));
			w53.RightAttach = ((uint)(2));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlMain.Gtk.Table+TableChild
			this.pnlMainStyle = new global::Gtk.Table (((uint)(1)), ((uint)(5)), false);
			this.pnlMainStyle.Name = "pnlMainStyle";
			this.pnlMainStyle.RowSpacing = ((uint)(3));
			this.pnlMainStyle.ColumnSpacing = ((uint)(3));
			// Container child pnlMainStyle.Gtk.Table+TableChild
			this.cmdMainBG = new global::Gtk.ColorButton ();
			this.cmdMainBG.CanFocus = true;
			this.cmdMainBG.Events = ((global::Gdk.EventMask)(784));
			this.cmdMainBG.Name = "cmdMainBG";
			this.cmdMainBG.Title = global::Mono.Unix.Catalog.GetString ("Main Graph Background Color");
			this.pnlMainStyle.Add (this.cmdMainBG);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.pnlMainStyle [this.cmdMainBG]));
			w54.LeftAttach = ((uint)(4));
			w54.RightAttach = ((uint)(5));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlMainStyle.Gtk.Table+TableChild
			this.cmdMainText = new global::Gtk.ColorButton ();
			this.cmdMainText.CanFocus = true;
			this.cmdMainText.Events = ((global::Gdk.EventMask)(784));
			this.cmdMainText.Name = "cmdMainText";
			this.cmdMainText.Title = global::Mono.Unix.Catalog.GetString ("Main Graph Text Color");
			this.pnlMainStyle.Add (this.cmdMainText);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.pnlMainStyle [this.cmdMainText]));
			w55.LeftAttach = ((uint)(1));
			w55.RightAttach = ((uint)(2));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlMainStyle.Gtk.Table+TableChild
			this.lblMainBG = new global::Gtk.Label ();
			this.lblMainBG.Name = "lblMainBG";
			this.lblMainBG.Xalign = 0F;
			this.lblMainBG.LabelProp = global::Mono.Unix.Catalog.GetString ("Background:");
			this.pnlMainStyle.Add (this.lblMainBG);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.pnlMainStyle [this.lblMainBG]));
			w56.LeftAttach = ((uint)(3));
			w56.RightAttach = ((uint)(4));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlMainStyle.Gtk.Table+TableChild
			this.lblMainText = new global::Gtk.Label ();
			this.lblMainText.Name = "lblMainText";
			this.lblMainText.Xalign = 0F;
			this.lblMainText.LabelProp = global::Mono.Unix.Catalog.GetString ("Text Color:");
			this.pnlMainStyle.Add (this.lblMainText);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.pnlMainStyle [this.lblMainText]));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			this.pnlMain.Add (this.pnlMainStyle);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.pnlMain [this.pnlMainStyle]));
			w58.TopAttach = ((uint)(1));
			w58.BottomAttach = ((uint)(2));
			w58.RightAttach = ((uint)(2));
			w58.XOptions = ((global::Gtk.AttachOptions)(4));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			this.algnMain.Add (this.pnlMain);
			this.grpMain.Add (this.algnMain);
			this.lblMainTitle = new global::Gtk.Label ();
			this.lblMainTitle.Name = "lblMainTitle";
			this.lblMainTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Main Window Current Usage Graphs");
			this.lblMainTitle.UseMarkup = true;
			this.grpMain.LabelWidget = this.lblMainTitle;
			this.pnlCustomColors.Add (this.grpMain);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.pnlCustomColors [this.grpMain]));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlCustomColors.Gtk.Table+TableChild
			this.grpTray = new global::Gtk.Frame ();
			this.grpTray.Name = "grpTray";
			// Container child grpTray.Gtk.Container+ContainerChild
			this.algnTray = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.algnTray.Name = "algnTray";
			this.algnTray.LeftPadding = ((uint)(3));
			this.algnTray.TopPadding = ((uint)(3));
			this.algnTray.RightPadding = ((uint)(3));
			this.algnTray.BottomPadding = ((uint)(3));
			// Container child algnTray.Gtk.Container+ContainerChild
			this.pnlTray = new global::Gtk.Table (((uint)(1)), ((uint)(3)), false);
			this.pnlTray.Name = "pnlTray";
			this.pnlTray.RowSpacing = ((uint)(3));
			this.pnlTray.ColumnSpacing = ((uint)(3));
			// Container child pnlTray.Gtk.Table+TableChild
			this.evnTray = new global::Gtk.EventBox ();
			this.evnTray.Name = "evnTray";
			// Container child evnTray.Gtk.Container+ContainerChild
			this.pctTray = new global::Gtk.Image ();
			this.pctTray.WidthRequest = 75;
			this.pctTray.HeightRequest = 75;
			this.pctTray.Name = "pctTray";
			this.evnTray.Add (this.pctTray);
			this.pnlTray.Add (this.evnTray);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.pnlTray [this.evnTray]));
			w63.LeftAttach = ((uint)(2));
			w63.RightAttach = ((uint)(3));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlTray.Gtk.Table+TableChild
			this.grpTrayDown = new global::Gtk.Frame ();
			this.grpTrayDown.Name = "grpTrayDown";
			this.grpTrayDown.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child grpTrayDown.Gtk.Container+ContainerChild
			this.algnTrayDown = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.algnTrayDown.Name = "algnTrayDown";
			this.algnTrayDown.LeftPadding = ((uint)(3));
			this.algnTrayDown.TopPadding = ((uint)(3));
			this.algnTrayDown.RightPadding = ((uint)(3));
			this.algnTrayDown.BottomPadding = ((uint)(3));
			// Container child algnTrayDown.Gtk.Container+ContainerChild
			this.pnlTrayDown = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.pnlTrayDown.Name = "pnlTrayDown";
			this.pnlTrayDown.RowSpacing = ((uint)(3));
			this.pnlTrayDown.ColumnSpacing = ((uint)(3));
			// Container child pnlTrayDown.Gtk.Table+TableChild
			this.chkTrayDownB = new global::Gtk.CheckButton ();
			this.chkTrayDownB.CanFocus = true;
			this.chkTrayDownB.Name = "chkTrayDownB";
			this.chkTrayDownB.Label = global::Mono.Unix.Catalog.GetString ("50% :");
			this.chkTrayDownB.Active = true;
			this.chkTrayDownB.DrawIndicator = true;
			this.chkTrayDownB.UseUnderline = true;
			this.pnlTrayDown.Add (this.chkTrayDownB);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.pnlTrayDown [this.chkTrayDownB]));
			w64.TopAttach = ((uint)(1));
			w64.BottomAttach = ((uint)(2));
			w64.XOptions = ((global::Gtk.AttachOptions)(0));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlTrayDown.Gtk.Table+TableChild
			this.cmdTrayDownA = new global::Gtk.ColorButton ();
			this.cmdTrayDownA.CanFocus = true;
			this.cmdTrayDownA.Events = ((global::Gdk.EventMask)(784));
			this.cmdTrayDownA.Name = "cmdTrayDownA";
			this.cmdTrayDownA.Title = global::Mono.Unix.Catalog.GetString ("Tray Graph Download 0% Color");
			this.pnlTrayDown.Add (this.cmdTrayDownA);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.pnlTrayDown [this.cmdTrayDownA]));
			w65.LeftAttach = ((uint)(2));
			w65.RightAttach = ((uint)(3));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlTrayDown.Gtk.Table+TableChild
			this.cmdTrayDownB = new global::Gtk.ColorButton ();
			this.cmdTrayDownB.CanFocus = true;
			this.cmdTrayDownB.Events = ((global::Gdk.EventMask)(784));
			this.cmdTrayDownB.Name = "cmdTrayDownB";
			this.cmdTrayDownB.Title = global::Mono.Unix.Catalog.GetString ("Tray Graph Download 50% Color");
			this.pnlTrayDown.Add (this.cmdTrayDownB);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.pnlTrayDown [this.cmdTrayDownB]));
			w66.TopAttach = ((uint)(1));
			w66.BottomAttach = ((uint)(2));
			w66.LeftAttach = ((uint)(2));
			w66.RightAttach = ((uint)(3));
			w66.XOptions = ((global::Gtk.AttachOptions)(4));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlTrayDown.Gtk.Table+TableChild
			this.cmdTrayDownC = new global::Gtk.ColorButton ();
			this.cmdTrayDownC.CanFocus = true;
			this.cmdTrayDownC.Events = ((global::Gdk.EventMask)(784));
			this.cmdTrayDownC.Name = "cmdTrayDownC";
			this.cmdTrayDownC.Title = global::Mono.Unix.Catalog.GetString ("Tray Graph Download 100% Color");
			this.pnlTrayDown.Add (this.cmdTrayDownC);
			global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.pnlTrayDown [this.cmdTrayDownC]));
			w67.TopAttach = ((uint)(2));
			w67.BottomAttach = ((uint)(3));
			w67.LeftAttach = ((uint)(2));
			w67.RightAttach = ((uint)(3));
			w67.XOptions = ((global::Gtk.AttachOptions)(4));
			w67.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlTrayDown.Gtk.Table+TableChild
			this.lblTrayDownA = new global::Gtk.Label ();
			this.lblTrayDownA.Name = "lblTrayDownA";
			this.lblTrayDownA.Xalign = 1F;
			this.lblTrayDownA.LabelProp = global::Mono.Unix.Catalog.GetString ("0% :");
			this.pnlTrayDown.Add (this.lblTrayDownA);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.pnlTrayDown [this.lblTrayDownA]));
			w68.XOptions = ((global::Gtk.AttachOptions)(4));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlTrayDown.Gtk.Table+TableChild
			this.lblTrayDownC = new global::Gtk.Label ();
			this.lblTrayDownC.Name = "lblTrayDownC";
			this.lblTrayDownC.Xalign = 1F;
			this.lblTrayDownC.LabelProp = global::Mono.Unix.Catalog.GetString ("100% :");
			this.pnlTrayDown.Add (this.lblTrayDownC);
			global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.pnlTrayDown [this.lblTrayDownC]));
			w69.TopAttach = ((uint)(2));
			w69.BottomAttach = ((uint)(3));
			w69.XOptions = ((global::Gtk.AttachOptions)(4));
			w69.YOptions = ((global::Gtk.AttachOptions)(4));
			this.algnTrayDown.Add (this.pnlTrayDown);
			this.grpTrayDown.Add (this.algnTrayDown);
			this.lblTrayDownTitle = new global::Gtk.Label ();
			this.lblTrayDownTitle.Name = "lblTrayDownTitle";
			this.lblTrayDownTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Download Colors");
			this.lblTrayDownTitle.UseMarkup = true;
			this.grpTrayDown.LabelWidget = this.lblTrayDownTitle;
			this.pnlTray.Add (this.grpTrayDown);
			global::Gtk.Table.TableChild w72 = ((global::Gtk.Table.TableChild)(this.pnlTray [this.grpTrayDown]));
			w72.XOptions = ((global::Gtk.AttachOptions)(4));
			w72.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlTray.Gtk.Table+TableChild
			this.grpTrayUp = new global::Gtk.Frame ();
			this.grpTrayUp.Name = "grpTrayUp";
			this.grpTrayUp.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child grpTrayUp.Gtk.Container+ContainerChild
			this.algnTrayUp = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.algnTrayUp.Name = "algnTrayUp";
			this.algnTrayUp.LeftPadding = ((uint)(3));
			this.algnTrayUp.TopPadding = ((uint)(3));
			this.algnTrayUp.RightPadding = ((uint)(3));
			this.algnTrayUp.BottomPadding = ((uint)(3));
			// Container child algnTrayUp.Gtk.Container+ContainerChild
			this.pnlTrayUp = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.pnlTrayUp.Name = "pnlTrayUp";
			this.pnlTrayUp.RowSpacing = ((uint)(3));
			this.pnlTrayUp.ColumnSpacing = ((uint)(3));
			// Container child pnlTrayUp.Gtk.Table+TableChild
			this.chkTrayUpB = new global::Gtk.CheckButton ();
			this.chkTrayUpB.CanFocus = true;
			this.chkTrayUpB.Name = "chkTrayUpB";
			this.chkTrayUpB.Label = global::Mono.Unix.Catalog.GetString ("50% :");
			this.chkTrayUpB.Active = true;
			this.chkTrayUpB.DrawIndicator = true;
			this.chkTrayUpB.UseUnderline = true;
			this.pnlTrayUp.Add (this.chkTrayUpB);
			global::Gtk.Table.TableChild w73 = ((global::Gtk.Table.TableChild)(this.pnlTrayUp [this.chkTrayUpB]));
			w73.TopAttach = ((uint)(1));
			w73.BottomAttach = ((uint)(2));
			w73.XOptions = ((global::Gtk.AttachOptions)(0));
			w73.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlTrayUp.Gtk.Table+TableChild
			this.cmdTrayUpA = new global::Gtk.ColorButton ();
			this.cmdTrayUpA.CanFocus = true;
			this.cmdTrayUpA.Events = ((global::Gdk.EventMask)(784));
			this.cmdTrayUpA.Name = "cmdTrayUpA";
			this.cmdTrayUpA.Title = global::Mono.Unix.Catalog.GetString ("Tray Graph Upload 0% Color");
			this.pnlTrayUp.Add (this.cmdTrayUpA);
			global::Gtk.Table.TableChild w74 = ((global::Gtk.Table.TableChild)(this.pnlTrayUp [this.cmdTrayUpA]));
			w74.LeftAttach = ((uint)(2));
			w74.RightAttach = ((uint)(3));
			w74.XOptions = ((global::Gtk.AttachOptions)(4));
			w74.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlTrayUp.Gtk.Table+TableChild
			this.cmdTrayUpB = new global::Gtk.ColorButton ();
			this.cmdTrayUpB.CanFocus = true;
			this.cmdTrayUpB.Events = ((global::Gdk.EventMask)(784));
			this.cmdTrayUpB.Name = "cmdTrayUpB";
			this.cmdTrayUpB.Title = global::Mono.Unix.Catalog.GetString ("Tray Graph Upload 50% Color");
			this.pnlTrayUp.Add (this.cmdTrayUpB);
			global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.pnlTrayUp [this.cmdTrayUpB]));
			w75.TopAttach = ((uint)(1));
			w75.BottomAttach = ((uint)(2));
			w75.LeftAttach = ((uint)(2));
			w75.RightAttach = ((uint)(3));
			w75.XOptions = ((global::Gtk.AttachOptions)(4));
			w75.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlTrayUp.Gtk.Table+TableChild
			this.cmdTrayUpC = new global::Gtk.ColorButton ();
			this.cmdTrayUpC.CanFocus = true;
			this.cmdTrayUpC.Events = ((global::Gdk.EventMask)(784));
			this.cmdTrayUpC.Name = "cmdTrayUpC";
			this.cmdTrayUpC.Title = global::Mono.Unix.Catalog.GetString ("Tray Graph Upload 100% Color");
			this.pnlTrayUp.Add (this.cmdTrayUpC);
			global::Gtk.Table.TableChild w76 = ((global::Gtk.Table.TableChild)(this.pnlTrayUp [this.cmdTrayUpC]));
			w76.TopAttach = ((uint)(2));
			w76.BottomAttach = ((uint)(3));
			w76.LeftAttach = ((uint)(2));
			w76.RightAttach = ((uint)(3));
			w76.XOptions = ((global::Gtk.AttachOptions)(4));
			w76.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlTrayUp.Gtk.Table+TableChild
			this.lblTrayUpA = new global::Gtk.Label ();
			this.lblTrayUpA.Name = "lblTrayUpA";
			this.lblTrayUpA.Xalign = 1F;
			this.lblTrayUpA.LabelProp = global::Mono.Unix.Catalog.GetString ("0% :");
			this.pnlTrayUp.Add (this.lblTrayUpA);
			global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.pnlTrayUp [this.lblTrayUpA]));
			w77.XOptions = ((global::Gtk.AttachOptions)(4));
			w77.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlTrayUp.Gtk.Table+TableChild
			this.lblTrayUpC = new global::Gtk.Label ();
			this.lblTrayUpC.Name = "lblTrayUpC";
			this.lblTrayUpC.Xalign = 1F;
			this.lblTrayUpC.LabelProp = global::Mono.Unix.Catalog.GetString ("100% :");
			this.pnlTrayUp.Add (this.lblTrayUpC);
			global::Gtk.Table.TableChild w78 = ((global::Gtk.Table.TableChild)(this.pnlTrayUp [this.lblTrayUpC]));
			w78.TopAttach = ((uint)(2));
			w78.BottomAttach = ((uint)(3));
			w78.XOptions = ((global::Gtk.AttachOptions)(4));
			w78.YOptions = ((global::Gtk.AttachOptions)(4));
			this.algnTrayUp.Add (this.pnlTrayUp);
			this.grpTrayUp.Add (this.algnTrayUp);
			this.lblTrayUpTitle = new global::Gtk.Label ();
			this.lblTrayUpTitle.Name = "lblTrayUpTitle";
			this.lblTrayUpTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Upload Colors");
			this.lblTrayUpTitle.UseMarkup = true;
			this.grpTrayUp.LabelWidget = this.lblTrayUpTitle;
			this.pnlTray.Add (this.grpTrayUp);
			global::Gtk.Table.TableChild w81 = ((global::Gtk.Table.TableChild)(this.pnlTray [this.grpTrayUp]));
			w81.LeftAttach = ((uint)(1));
			w81.RightAttach = ((uint)(2));
			w81.XOptions = ((global::Gtk.AttachOptions)(4));
			w81.YOptions = ((global::Gtk.AttachOptions)(4));
			this.algnTray.Add (this.pnlTray);
			this.grpTray.Add (this.algnTray);
			this.lblTrayTitle = new global::Gtk.Label ();
			this.lblTrayTitle.Name = "lblTrayTitle";
			this.lblTrayTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Tray Icon Current Usage Graph Overlay");
			this.lblTrayTitle.UseMarkup = true;
			this.grpTray.LabelWidget = this.lblTrayTitle;
			this.pnlCustomColors.Add (this.grpTray);
			global::Gtk.Table.TableChild w84 = ((global::Gtk.Table.TableChild)(this.pnlCustomColors [this.grpTray]));
			w84.TopAttach = ((uint)(1));
			w84.BottomAttach = ((uint)(2));
			w84.XOptions = ((global::Gtk.AttachOptions)(4));
			w84.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.pnlCustomColors);
			global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(w1 [this.pnlCustomColors]));
			w85.Position = 0;
			w85.Expand = false;
			w85.Fill = false;
			// Internal child RestrictionTrackerGTK.dlgCustomColors.ActionArea
			global::Gtk.HButtonBox w86 = this.ActionArea;
			w86.Name = "pnlColorButtons";
			w86.Spacing = 10;
			w86.BorderWidth = ((uint)(3));
			w86.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child pnlColorButtons.Gtk.ButtonBox+ButtonBoxChild
			this.cmdSave = new global::Gtk.Button ();
			this.cmdSave.CanDefault = true;
			this.cmdSave.CanFocus = true;
			this.cmdSave.Name = "cmdSave";
			this.cmdSave.UseUnderline = true;
			// Container child cmdSave.Gtk.Container+ContainerChild
			global::Gtk.Alignment w87 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w88 = new global::Gtk.HBox ();
			w88.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w89 = new global::Gtk.Image ();
			w89.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save", global::Gtk.IconSize.Button);
			w88.Add (w89);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w91 = new global::Gtk.Label ();
			w91.LabelProp = global::Mono.Unix.Catalog.GetString ("_Save");
			w91.UseUnderline = true;
			w88.Add (w91);
			w87.Add (w88);
			this.cmdSave.Add (w87);
			w86.Add (this.cmdSave);
			global::Gtk.ButtonBox.ButtonBoxChild w95 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w86 [this.cmdSave]));
			w95.Expand = false;
			w95.Fill = false;
			// Container child pnlColorButtons.Gtk.ButtonBox+ButtonBoxChild
			this.cmdClose = new global::Gtk.Button ();
			this.cmdClose.CanDefault = true;
			this.cmdClose.CanFocus = true;
			this.cmdClose.Name = "cmdClose";
			this.cmdClose.UseUnderline = true;
			// Container child cmdClose.Gtk.Container+ContainerChild
			global::Gtk.Alignment w96 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w97 = new global::Gtk.HBox ();
			w97.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w98 = new global::Gtk.Image ();
			w98.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Button);
			w97.Add (w98);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w100 = new global::Gtk.Label ();
			w100.LabelProp = global::Mono.Unix.Catalog.GetString ("_Close");
			w100.UseUnderline = true;
			w97.Add (w100);
			w96.Add (w97);
			this.cmdClose.Add (w96);
			w86.Add (this.cmdClose);
			global::Gtk.ButtonBox.ButtonBoxChild w104 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w86 [this.cmdClose]));
			w104.Position = 1;
			w104.Expand = false;
			w104.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 345;
			this.DefaultHeight = 567;
			this.Hide ();
			this.evnTray.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.pctTray_MouseUp);
			this.evnMain.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.pctMain_MouseUp);
			this.cmdSave.Clicked += new global::System.EventHandler (this.cmdSave_Click);
			this.cmdClose.Clicked += new global::System.EventHandler (this.cmdClose_Click);
		}
	}
}
