
// This file has been generated by the GUI designer. Do not modify.
namespace RestrictionTrackerGTK
{
	public partial class frmAbout
	{
		private global::Gtk.HBox pnlAbout;
		private global::Gtk.Image LogoPictureBox;
		private global::Gtk.VBox pnlText;
		private global::Gtk.Label lblProduct;
		private global::Gtk.Label lblVersion;
		private global::Gtk.HBox pnlUpdate;
		private global::Gtk.Image pctUpdate;
		private global::Gtk.Label lblUpdate;
		private global::Gtk.Label lblCompany;
		private global::Gtk.ScrolledWindow scrlDescription;
		private global::Gtk.TextView txtDescription;
		private global::Gtk.HBox pnlButtons;
		private global::Gtk.Button cmdDonate;
		private global::Gtk.Button cmdOK;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RestrictionTrackerGTK.frmAbout
			this.WidthRequest = 420;
			this.HeightRequest = 300;
			this.Name = "RestrictionTrackerGTK.frmAbout";
			this.Title = global::Mono.Unix.Catalog.GetString ("About Satellite Restriction Tracker");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("RestrictionTrackerGTK.Resources.norm.ico");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(9));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 420;
			this.DefaultHeight = 300;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Container child RestrictionTrackerGTK.frmAbout.Gtk.Container+ContainerChild
			this.pnlAbout = new global::Gtk.HBox ();
			this.pnlAbout.Name = "pnlAbout";
			this.pnlAbout.Spacing = 6;
			// Container child pnlAbout.Gtk.Box+BoxChild
			this.LogoPictureBox = new global::Gtk.Image ();
			this.LogoPictureBox.WidthRequest = 124;
			this.LogoPictureBox.HeightRequest = 242;
			this.LogoPictureBox.Name = "LogoPictureBox";
			this.LogoPictureBox.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("RestrictionTrackerGTK.Resources.side.jpg");
			this.pnlAbout.Add (this.LogoPictureBox);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.pnlAbout [this.LogoPictureBox]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child pnlAbout.Gtk.Box+BoxChild
			this.pnlText = new global::Gtk.VBox ();
			this.pnlText.Name = "pnlText";
			this.pnlText.Spacing = 6;
			// Container child pnlText.Gtk.Box+BoxChild
			this.lblProduct = new global::Gtk.Label ();
			this.lblProduct.Name = "lblProduct";
			this.lblProduct.Xalign = 0F;
			this.lblProduct.LabelProp = global::Mono.Unix.Catalog.GetString ("Product Name");
			this.pnlText.Add (this.lblProduct);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.pnlText [this.lblProduct]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child pnlText.Gtk.Box+BoxChild
			this.lblVersion = new global::Gtk.Label ();
			this.lblVersion.Name = "lblVersion";
			this.lblVersion.Xalign = 0F;
			this.lblVersion.LabelProp = global::Mono.Unix.Catalog.GetString ("Version");
			this.pnlText.Add (this.lblVersion);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.pnlText [this.lblVersion]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child pnlText.Gtk.Box+BoxChild
			this.pnlUpdate = new global::Gtk.HBox ();
			this.pnlUpdate.Name = "pnlUpdate";
			this.pnlUpdate.Spacing = 6;
			// Container child pnlUpdate.Gtk.Box+BoxChild
			this.pctUpdate = new global::Gtk.Image ();
			this.pctUpdate.WidthRequest = 16;
			this.pctUpdate.HeightRequest = 16;
			this.pctUpdate.Name = "pctUpdate";
			this.pnlUpdate.Add (this.pctUpdate);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.pnlUpdate [this.pctUpdate]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child pnlUpdate.Gtk.Box+BoxChild
			this.lblUpdate = new global::Gtk.Label ();
			this.lblUpdate.Name = "lblUpdate";
			this.lblUpdate.Xalign = 0F;
			this.lblUpdate.LabelProp = global::Mono.Unix.Catalog.GetString ("No New Updates");
			this.pnlUpdate.Add (this.lblUpdate);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.pnlUpdate [this.lblUpdate]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.pnlText.Add (this.pnlUpdate);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.pnlText [this.pnlUpdate]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child pnlText.Gtk.Box+BoxChild
			this.lblCompany = new global::Gtk.Label ();
			this.lblCompany.Name = "lblCompany";
			this.lblCompany.Xalign = 0F;
			this.lblCompany.LabelProp = global::Mono.Unix.Catalog.GetString ("Company Name");
			this.pnlText.Add (this.lblCompany);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.pnlText [this.lblCompany]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			// Container child pnlText.Gtk.Box+BoxChild
			this.scrlDescription = new global::Gtk.ScrolledWindow ();
			this.scrlDescription.Name = "scrlDescription";
			this.scrlDescription.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.scrlDescription.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrlDescription.Gtk.Container+ContainerChild
			this.txtDescription = new global::Gtk.TextView ();
			this.txtDescription.CanFocus = true;
			this.txtDescription.Name = "txtDescription";
			this.txtDescription.Editable = false;
			this.txtDescription.WrapMode = ((global::Gtk.WrapMode)(2));
			this.scrlDescription.Add (this.txtDescription);
			this.pnlText.Add (this.scrlDescription);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.pnlText [this.scrlDescription]));
			w9.Position = 4;
			// Container child pnlText.Gtk.Box+BoxChild
			this.pnlButtons = new global::Gtk.HBox ();
			this.pnlButtons.Name = "pnlButtons";
			this.pnlButtons.Spacing = 6;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.cmdDonate = new global::Gtk.Button ();
			this.cmdDonate.CanFocus = true;
			this.cmdDonate.Name = "cmdDonate";
			this.cmdDonate.UseUnderline = true;
			// Container child cmdDonate.Gtk.Container+ContainerChild
			global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w11 = new global::Gtk.HBox ();
			w11.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Button);
			w11.Add (w12);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w14 = new global::Gtk.Label ();
			w14.LabelProp = global::Mono.Unix.Catalog.GetString ("Make a Donation");
			w14.UseUnderline = true;
			w11.Add (w14);
			w10.Add (w11);
			this.cmdDonate.Add (w10);
			this.pnlButtons.Add (this.cmdDonate);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.pnlButtons [this.cmdDonate]));
			w18.Position = 0;
			w18.Fill = false;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.cmdOK = new global::Gtk.Button ();
			this.cmdOK.WidthRequest = 75;
			this.cmdOK.CanFocus = true;
			this.cmdOK.Name = "cmdOK";
			this.cmdOK.UseUnderline = true;
			// Container child cmdOK.Gtk.Container+ContainerChild
			global::Gtk.Alignment w19 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w20 = new global::Gtk.HBox ();
			w20.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w21 = new global::Gtk.Image ();
			w21.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-ok", global::Gtk.IconSize.Button);
			w20.Add (w21);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w23 = new global::Gtk.Label ();
			w23.LabelProp = global::Mono.Unix.Catalog.GetString ("_OK");
			w23.UseUnderline = true;
			w20.Add (w23);
			w19.Add (w20);
			this.cmdOK.Add (w19);
			this.pnlButtons.Add (this.cmdOK);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.pnlButtons [this.cmdOK]));
			w27.PackType = ((global::Gtk.PackType)(1));
			w27.Position = 1;
			w27.Fill = false;
			this.pnlText.Add (this.pnlButtons);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.pnlText [this.pnlButtons]));
			w28.Position = 5;
			w28.Expand = false;
			w28.Fill = false;
			this.pnlAbout.Add (this.pnlText);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.pnlAbout [this.pnlText]));
			w29.Position = 1;
			this.Add (this.pnlAbout);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.pctUpdate.Hide ();
			this.Show ();
			this.Hidden += new global::System.EventHandler (this.OnHidden);
			this.cmdDonate.Clicked += new global::System.EventHandler (this.cmdDonate_Click);
			this.cmdOK.Clicked += new global::System.EventHandler (this.cmdOK_Click);
		}
	}
}
