
// This file has been generated by the GUI designer. Do not modify.
namespace RestrictionTrackerGTK
{
	public partial class frmMain
	{
		private global::Gtk.VBox pnlDetails;

		private global::Gtk.HBox pnlButtons;

		private global::Gtk.Button cmdRefresh;

		private global::Gtk.Button cmdHistory;

		private global::Gtk.Button cmdConfig;

		private global::Gtk.Button cmdAbout;

		private global::Gtk.Frame gbUsage;

		private global::Gtk.Alignment algnUsage;

		private global::Gtk.VBox pnlDisplays;

		private global::Gtk.VBox pnlNothing;

		private global::Gtk.Label lblNothing;

		private global::Gtk.Label lblRRS;

		private global::Gtk.HBox pnlTypeA;

		private global::Gtk.Frame gbTypeADld;

		private global::Gtk.Alignment algnTypeADld;

		private global::Gtk.HBox pnlTypeADld;

		private global::Gtk.VBox pnlDldText;

		private global::Gtk.HBox pnlDldTextUsed;

		private global::Gtk.Label lblTypeADldUsed;

		private global::Gtk.Label lblTypeADldUsedVal;

		private global::Gtk.HBox pnlDldTextFree;

		private global::Gtk.Label lblTypeADldFree;

		private global::Gtk.Label lblTypeADldFreeVal;

		private global::Gtk.HBox pnlDldTextLimit;

		private global::Gtk.Label lblTypeADldLimit;

		private global::Gtk.Label lblTypeADldLimitVal;

		private global::Gtk.EventBox evnTypeADld;

		private global::Gtk.Image pctTypeADld;

		private global::Gtk.Label lblTypeADld;

		private global::Gtk.Frame gbTypeAUld;

		private global::Gtk.Alignment algnTypeAUld;

		private global::Gtk.HBox pnlTypeAUld;

		private global::Gtk.VBox pnlUldText;

		private global::Gtk.HBox pnlUldTextUsed;

		private global::Gtk.Label lblTypeAUldUsed;

		private global::Gtk.Label lblTypeAUldUsedVal;

		private global::Gtk.HBox pnlUldTextFree;

		private global::Gtk.Label lblTypeAUldFree;

		private global::Gtk.Label lblTypeAUldFreeVal;

		private global::Gtk.HBox pnlUldTextLimit;

		private global::Gtk.Label lblTypeAUldLimit;

		private global::Gtk.Label lblTypeAUldLimitVal;

		private global::Gtk.EventBox evnTypeAUld;

		private global::Gtk.Image pctTypeAUld;

		private global::Gtk.Label lblTypeAUld;

		private global::Gtk.HBox pnlTypeB;

		private global::Gtk.VBox pnlRuralNumbers;

		private global::Gtk.HBox pnlRuralUsed;

		private global::Gtk.Label lblTypeBUsed;

		private global::Gtk.Label lblTypeBUsedVal;

		private global::Gtk.HBox pnlRuralFree;

		private global::Gtk.Label lblTypeBFree;

		private global::Gtk.Label lblTypeBFreeVal;

		private global::Gtk.HBox pnlRuralTotal;

		private global::Gtk.Label lblTypeBLimit;

		private global::Gtk.Label lblTypeBLimitVal;

		private global::Gtk.EventBox evnTypeB;

		private global::Gtk.Image pctTypeB;

		private global::Gtk.Label lblStatus;

		private global::Gtk.Statusbar sbMainStatus;

		private global::Gtk.ProgressBar pbMainStatus;

		private global::Gtk.Button cmdNetTest;

		private global::Gtk.Label lblMainStatus;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RestrictionTrackerGTK.frmMain
			this.Name = "RestrictionTrackerGTK.frmMain";
			this.Title = global::Mono.Unix.Catalog.GetString("Satellite Restriction Tracker");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("RestrictionTrackerGTK.Resources.norm.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.AllowShrink = true;
			this.Role = "";
			// Container child RestrictionTrackerGTK.frmMain.Gtk.Container+ContainerChild
			this.pnlDetails = new global::Gtk.VBox();
			this.pnlDetails.Name = "pnlDetails";
			// Container child pnlDetails.Gtk.Box+BoxChild
			this.pnlButtons = new global::Gtk.HBox();
			this.pnlButtons.Name = "pnlButtons";
			this.pnlButtons.Homogeneous = true;
			this.pnlButtons.Spacing = 3;
			this.pnlButtons.BorderWidth = ((uint)(3));
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.cmdRefresh = new global::Gtk.Button();
			this.cmdRefresh.TooltipMarkup = "Reload bandwidth level information immediately.\n(Hold CTRL to reload database.)";
			this.cmdRefresh.CanFocus = true;
			this.cmdRefresh.Name = "cmdRefresh";
			this.cmdRefresh.UseUnderline = true;
			this.cmdRefresh.Label = global::Mono.Unix.Catalog.GetString("_Refresh");
			this.pnlButtons.Add(this.cmdRefresh);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.pnlButtons[this.cmdRefresh]));
			w1.Position = 0;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.cmdHistory = new global::Gtk.Button();
			this.cmdHistory.TooltipMarkup = "View your bandwidth history.";
			this.cmdHistory.CanFocus = true;
			this.cmdHistory.Name = "cmdHistory";
			this.cmdHistory.UseUnderline = true;
			this.cmdHistory.Label = global::Mono.Unix.Catalog.GetString("_History");
			this.pnlButtons.Add(this.cmdHistory);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.pnlButtons[this.cmdHistory]));
			w2.Position = 1;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.cmdConfig = new global::Gtk.Button();
			this.cmdConfig.TooltipMarkup = "Change program settings.";
			this.cmdConfig.CanFocus = true;
			this.cmdConfig.Name = "cmdConfig";
			this.cmdConfig.UseUnderline = true;
			this.cmdConfig.Label = global::Mono.Unix.Catalog.GetString("_Configuration");
			this.pnlButtons.Add(this.cmdConfig);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.pnlButtons[this.cmdConfig]));
			w3.Position = 2;
			// Container child pnlButtons.Gtk.Box+BoxChild
			this.cmdAbout = new global::Gtk.Button();
			this.cmdAbout.TooltipMarkup = "View information about Satellite Restriction Tracker and check for updates.";
			this.cmdAbout.CanFocus = true;
			this.cmdAbout.Name = "cmdAbout";
			this.cmdAbout.UseUnderline = true;
			this.cmdAbout.Label = global::Mono.Unix.Catalog.GetString("_About");
			this.pnlButtons.Add(this.cmdAbout);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.pnlButtons[this.cmdAbout]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 3;
			this.pnlDetails.Add(this.pnlButtons);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.pnlDetails[this.pnlButtons]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child pnlDetails.Gtk.Box+BoxChild
			this.gbUsage = new global::Gtk.Frame();
			this.gbUsage.Name = "gbUsage";
			this.gbUsage.BorderWidth = ((uint)(3));
			// Container child gbUsage.Gtk.Container+ContainerChild
			this.algnUsage = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.algnUsage.Name = "algnUsage";
			this.algnUsage.LeftPadding = ((uint)(3));
			this.algnUsage.TopPadding = ((uint)(3));
			this.algnUsage.RightPadding = ((uint)(3));
			this.algnUsage.BottomPadding = ((uint)(3));
			// Container child algnUsage.Gtk.Container+ContainerChild
			this.pnlDisplays = new global::Gtk.VBox();
			this.pnlDisplays.Name = "pnlDisplays";
			this.pnlDisplays.Spacing = 6;
			// Container child pnlDisplays.Gtk.Box+BoxChild
			this.pnlNothing = new global::Gtk.VBox();
			this.pnlNothing.Name = "pnlNothing";
			this.pnlNothing.Homogeneous = true;
			this.pnlNothing.Spacing = 6;
			// Container child pnlNothing.Gtk.Box+BoxChild
			this.lblNothing = new global::Gtk.Label();
			this.lblNothing.Name = "lblNothing";
			this.lblNothing.LabelProp = global::Mono.Unix.Catalog.GetString("Satellite Restriction Tracker");
			this.pnlNothing.Add(this.lblNothing);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.pnlNothing[this.lblNothing]));
			w6.Position = 0;
			// Container child pnlNothing.Gtk.Box+BoxChild
			this.lblRRS = new global::Gtk.Label();
			this.lblRRS.CanFocus = true;
			this.lblRRS.Name = "lblRRS";
			this.lblRRS.Xalign = 1F;
			this.lblRRS.LabelProp = global::Mono.Unix.Catalog.GetString("by RealityRipple Software");
			this.pnlNothing.Add(this.lblRRS);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.pnlNothing[this.lblRRS]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.pnlDisplays.Add(this.pnlNothing);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.pnlDisplays[this.pnlNothing]));
			w8.Position = 0;
			// Container child pnlDisplays.Gtk.Box+BoxChild
			this.pnlTypeA = new global::Gtk.HBox();
			this.pnlTypeA.Name = "pnlTypeA";
			this.pnlTypeA.Homogeneous = true;
			// Container child pnlTypeA.Gtk.Box+BoxChild
			this.gbTypeADld = new global::Gtk.Frame();
			this.gbTypeADld.Name = "gbTypeADld";
			this.gbTypeADld.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child gbTypeADld.Gtk.Container+ContainerChild
			this.algnTypeADld = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.algnTypeADld.Name = "algnTypeADld";
			this.algnTypeADld.LeftPadding = ((uint)(3));
			this.algnTypeADld.TopPadding = ((uint)(3));
			this.algnTypeADld.RightPadding = ((uint)(3));
			this.algnTypeADld.BottomPadding = ((uint)(3));
			// Container child algnTypeADld.Gtk.Container+ContainerChild
			this.pnlTypeADld = new global::Gtk.HBox();
			this.pnlTypeADld.Name = "pnlTypeADld";
			this.pnlTypeADld.Spacing = 6;
			// Container child pnlTypeADld.Gtk.Box+BoxChild
			this.pnlDldText = new global::Gtk.VBox();
			this.pnlDldText.Name = "pnlDldText";
			this.pnlDldText.Homogeneous = true;
			this.pnlDldText.Spacing = 6;
			// Container child pnlDldText.Gtk.Box+BoxChild
			this.pnlDldTextUsed = new global::Gtk.HBox();
			this.pnlDldTextUsed.Name = "pnlDldTextUsed";
			this.pnlDldTextUsed.Spacing = 6;
			// Container child pnlDldTextUsed.Gtk.Box+BoxChild
			this.lblTypeADldUsed = new global::Gtk.Label();
			this.lblTypeADldUsed.Name = "lblTypeADldUsed";
			this.lblTypeADldUsed.LabelProp = global::Mono.Unix.Catalog.GetString("Used:");
			this.pnlDldTextUsed.Add(this.lblTypeADldUsed);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.pnlDldTextUsed[this.lblTypeADldUsed]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child pnlDldTextUsed.Gtk.Box+BoxChild
			this.lblTypeADldUsedVal = new global::Gtk.Label();
			this.lblTypeADldUsedVal.Name = "lblTypeADldUsedVal";
			this.lblTypeADldUsedVal.LabelProp = global::Mono.Unix.Catalog.GetString(" -- ");
			this.pnlDldTextUsed.Add(this.lblTypeADldUsedVal);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.pnlDldTextUsed[this.lblTypeADldUsedVal]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.pnlDldText.Add(this.pnlDldTextUsed);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.pnlDldText[this.pnlDldTextUsed]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child pnlDldText.Gtk.Box+BoxChild
			this.pnlDldTextFree = new global::Gtk.HBox();
			this.pnlDldTextFree.Name = "pnlDldTextFree";
			this.pnlDldTextFree.Spacing = 6;
			// Container child pnlDldTextFree.Gtk.Box+BoxChild
			this.lblTypeADldFree = new global::Gtk.Label();
			this.lblTypeADldFree.Name = "lblTypeADldFree";
			this.lblTypeADldFree.LabelProp = global::Mono.Unix.Catalog.GetString("Free:");
			this.pnlDldTextFree.Add(this.lblTypeADldFree);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.pnlDldTextFree[this.lblTypeADldFree]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child pnlDldTextFree.Gtk.Box+BoxChild
			this.lblTypeADldFreeVal = new global::Gtk.Label();
			this.lblTypeADldFreeVal.Name = "lblTypeADldFreeVal";
			this.lblTypeADldFreeVal.LabelProp = global::Mono.Unix.Catalog.GetString(" -- ");
			this.pnlDldTextFree.Add(this.lblTypeADldFreeVal);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.pnlDldTextFree[this.lblTypeADldFreeVal]));
			w13.PackType = ((global::Gtk.PackType)(1));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.pnlDldText.Add(this.pnlDldTextFree);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.pnlDldText[this.pnlDldTextFree]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child pnlDldText.Gtk.Box+BoxChild
			this.pnlDldTextLimit = new global::Gtk.HBox();
			this.pnlDldTextLimit.Name = "pnlDldTextLimit";
			this.pnlDldTextLimit.Spacing = 6;
			// Container child pnlDldTextLimit.Gtk.Box+BoxChild
			this.lblTypeADldLimit = new global::Gtk.Label();
			this.lblTypeADldLimit.Name = "lblTypeADldLimit";
			this.lblTypeADldLimit.LabelProp = global::Mono.Unix.Catalog.GetString("Limit:");
			this.pnlDldTextLimit.Add(this.lblTypeADldLimit);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.pnlDldTextLimit[this.lblTypeADldLimit]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child pnlDldTextLimit.Gtk.Box+BoxChild
			this.lblTypeADldLimitVal = new global::Gtk.Label();
			this.lblTypeADldLimitVal.Name = "lblTypeADldLimitVal";
			this.lblTypeADldLimitVal.LabelProp = global::Mono.Unix.Catalog.GetString(" -- ");
			this.pnlDldTextLimit.Add(this.lblTypeADldLimitVal);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.pnlDldTextLimit[this.lblTypeADldLimitVal]));
			w16.PackType = ((global::Gtk.PackType)(1));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.pnlDldText.Add(this.pnlDldTextLimit);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.pnlDldText[this.pnlDldTextLimit]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.pnlTypeADld.Add(this.pnlDldText);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.pnlTypeADld[this.pnlDldText]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child pnlTypeADld.Gtk.Box+BoxChild
			this.evnTypeADld = new global::Gtk.EventBox();
			this.evnTypeADld.Name = "evnTypeADld";
			// Container child evnTypeADld.Gtk.Container+ContainerChild
			this.pctTypeADld = new global::Gtk.Image();
			this.pctTypeADld.TooltipMarkup = "Graph representing your download usage.";
			this.pctTypeADld.Name = "pctTypeADld";
			this.evnTypeADld.Add(this.pctTypeADld);
			this.pnlTypeADld.Add(this.evnTypeADld);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.pnlTypeADld[this.evnTypeADld]));
			w20.Position = 1;
			this.algnTypeADld.Add(this.pnlTypeADld);
			this.gbTypeADld.Add(this.algnTypeADld);
			this.lblTypeADld = new global::Gtk.Label();
			this.lblTypeADld.Name = "lblTypeADld";
			this.lblTypeADld.Xalign = 0F;
			this.lblTypeADld.LabelProp = global::Mono.Unix.Catalog.GetString("Download (X%)");
			this.lblTypeADld.UseMarkup = true;
			this.gbTypeADld.LabelWidget = this.lblTypeADld;
			this.pnlTypeA.Add(this.gbTypeADld);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.pnlTypeA[this.gbTypeADld]));
			w23.Position = 0;
			w23.Padding = ((uint)(3));
			// Container child pnlTypeA.Gtk.Box+BoxChild
			this.gbTypeAUld = new global::Gtk.Frame();
			this.gbTypeAUld.Name = "gbTypeAUld";
			this.gbTypeAUld.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child gbTypeAUld.Gtk.Container+ContainerChild
			this.algnTypeAUld = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.algnTypeAUld.Name = "algnTypeAUld";
			this.algnTypeAUld.LeftPadding = ((uint)(3));
			this.algnTypeAUld.TopPadding = ((uint)(3));
			this.algnTypeAUld.RightPadding = ((uint)(3));
			this.algnTypeAUld.BottomPadding = ((uint)(3));
			// Container child algnTypeAUld.Gtk.Container+ContainerChild
			this.pnlTypeAUld = new global::Gtk.HBox();
			this.pnlTypeAUld.Name = "pnlTypeAUld";
			this.pnlTypeAUld.Spacing = 6;
			// Container child pnlTypeAUld.Gtk.Box+BoxChild
			this.pnlUldText = new global::Gtk.VBox();
			this.pnlUldText.Name = "pnlUldText";
			this.pnlUldText.Homogeneous = true;
			this.pnlUldText.Spacing = 6;
			// Container child pnlUldText.Gtk.Box+BoxChild
			this.pnlUldTextUsed = new global::Gtk.HBox();
			this.pnlUldTextUsed.Name = "pnlUldTextUsed";
			this.pnlUldTextUsed.Spacing = 6;
			// Container child pnlUldTextUsed.Gtk.Box+BoxChild
			this.lblTypeAUldUsed = new global::Gtk.Label();
			this.lblTypeAUldUsed.Name = "lblTypeAUldUsed";
			this.lblTypeAUldUsed.LabelProp = global::Mono.Unix.Catalog.GetString("Used:");
			this.pnlUldTextUsed.Add(this.lblTypeAUldUsed);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.pnlUldTextUsed[this.lblTypeAUldUsed]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child pnlUldTextUsed.Gtk.Box+BoxChild
			this.lblTypeAUldUsedVal = new global::Gtk.Label();
			this.lblTypeAUldUsedVal.Name = "lblTypeAUldUsedVal";
			this.lblTypeAUldUsedVal.LabelProp = global::Mono.Unix.Catalog.GetString(" -- ");
			this.pnlUldTextUsed.Add(this.lblTypeAUldUsedVal);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.pnlUldTextUsed[this.lblTypeAUldUsedVal]));
			w25.PackType = ((global::Gtk.PackType)(1));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.pnlUldText.Add(this.pnlUldTextUsed);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.pnlUldText[this.pnlUldTextUsed]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child pnlUldText.Gtk.Box+BoxChild
			this.pnlUldTextFree = new global::Gtk.HBox();
			this.pnlUldTextFree.Name = "pnlUldTextFree";
			this.pnlUldTextFree.Spacing = 6;
			// Container child pnlUldTextFree.Gtk.Box+BoxChild
			this.lblTypeAUldFree = new global::Gtk.Label();
			this.lblTypeAUldFree.Name = "lblTypeAUldFree";
			this.lblTypeAUldFree.LabelProp = global::Mono.Unix.Catalog.GetString("Free:");
			this.pnlUldTextFree.Add(this.lblTypeAUldFree);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.pnlUldTextFree[this.lblTypeAUldFree]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child pnlUldTextFree.Gtk.Box+BoxChild
			this.lblTypeAUldFreeVal = new global::Gtk.Label();
			this.lblTypeAUldFreeVal.Name = "lblTypeAUldFreeVal";
			this.lblTypeAUldFreeVal.LabelProp = global::Mono.Unix.Catalog.GetString(" -- ");
			this.pnlUldTextFree.Add(this.lblTypeAUldFreeVal);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.pnlUldTextFree[this.lblTypeAUldFreeVal]));
			w28.PackType = ((global::Gtk.PackType)(1));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.pnlUldText.Add(this.pnlUldTextFree);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.pnlUldText[this.pnlUldTextFree]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			// Container child pnlUldText.Gtk.Box+BoxChild
			this.pnlUldTextLimit = new global::Gtk.HBox();
			this.pnlUldTextLimit.Name = "pnlUldTextLimit";
			this.pnlUldTextLimit.Spacing = 6;
			// Container child pnlUldTextLimit.Gtk.Box+BoxChild
			this.lblTypeAUldLimit = new global::Gtk.Label();
			this.lblTypeAUldLimit.Name = "lblTypeAUldLimit";
			this.lblTypeAUldLimit.LabelProp = global::Mono.Unix.Catalog.GetString("Limit:");
			this.pnlUldTextLimit.Add(this.lblTypeAUldLimit);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.pnlUldTextLimit[this.lblTypeAUldLimit]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child pnlUldTextLimit.Gtk.Box+BoxChild
			this.lblTypeAUldLimitVal = new global::Gtk.Label();
			this.lblTypeAUldLimitVal.Name = "lblTypeAUldLimitVal";
			this.lblTypeAUldLimitVal.LabelProp = global::Mono.Unix.Catalog.GetString(" -- ");
			this.pnlUldTextLimit.Add(this.lblTypeAUldLimitVal);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.pnlUldTextLimit[this.lblTypeAUldLimitVal]));
			w31.PackType = ((global::Gtk.PackType)(1));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.pnlUldText.Add(this.pnlUldTextLimit);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.pnlUldText[this.pnlUldTextLimit]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			this.pnlTypeAUld.Add(this.pnlUldText);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.pnlTypeAUld[this.pnlUldText]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child pnlTypeAUld.Gtk.Box+BoxChild
			this.evnTypeAUld = new global::Gtk.EventBox();
			this.evnTypeAUld.Name = "evnTypeAUld";
			// Container child evnTypeAUld.Gtk.Container+ContainerChild
			this.pctTypeAUld = new global::Gtk.Image();
			this.pctTypeAUld.TooltipMarkup = "Graph representing your upload usage.";
			this.pctTypeAUld.Name = "pctTypeAUld";
			this.evnTypeAUld.Add(this.pctTypeAUld);
			this.pnlTypeAUld.Add(this.evnTypeAUld);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.pnlTypeAUld[this.evnTypeAUld]));
			w35.Position = 1;
			this.algnTypeAUld.Add(this.pnlTypeAUld);
			this.gbTypeAUld.Add(this.algnTypeAUld);
			this.lblTypeAUld = new global::Gtk.Label();
			this.lblTypeAUld.Name = "lblTypeAUld";
			this.lblTypeAUld.Xalign = 0F;
			this.lblTypeAUld.LabelProp = global::Mono.Unix.Catalog.GetString("Upload (X%)");
			this.lblTypeAUld.UseMarkup = true;
			this.gbTypeAUld.LabelWidget = this.lblTypeAUld;
			this.pnlTypeA.Add(this.gbTypeAUld);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.pnlTypeA[this.gbTypeAUld]));
			w38.Position = 1;
			w38.Padding = ((uint)(3));
			this.pnlDisplays.Add(this.pnlTypeA);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.pnlDisplays[this.pnlTypeA]));
			w39.Position = 1;
			// Container child pnlDisplays.Gtk.Box+BoxChild
			this.pnlTypeB = new global::Gtk.HBox();
			this.pnlTypeB.Name = "pnlTypeB";
			this.pnlTypeB.Spacing = 6;
			// Container child pnlTypeB.Gtk.Box+BoxChild
			this.pnlRuralNumbers = new global::Gtk.VBox();
			this.pnlRuralNumbers.Name = "pnlRuralNumbers";
			this.pnlRuralNumbers.Homogeneous = true;
			this.pnlRuralNumbers.Spacing = 6;
			// Container child pnlRuralNumbers.Gtk.Box+BoxChild
			this.pnlRuralUsed = new global::Gtk.HBox();
			this.pnlRuralUsed.Name = "pnlRuralUsed";
			this.pnlRuralUsed.Spacing = 6;
			// Container child pnlRuralUsed.Gtk.Box+BoxChild
			this.lblTypeBUsed = new global::Gtk.Label();
			this.lblTypeBUsed.Name = "lblTypeBUsed";
			this.lblTypeBUsed.LabelProp = global::Mono.Unix.Catalog.GetString("Used:");
			this.pnlRuralUsed.Add(this.lblTypeBUsed);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.pnlRuralUsed[this.lblTypeBUsed]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child pnlRuralUsed.Gtk.Box+BoxChild
			this.lblTypeBUsedVal = new global::Gtk.Label();
			this.lblTypeBUsedVal.Name = "lblTypeBUsedVal";
			this.lblTypeBUsedVal.LabelProp = global::Mono.Unix.Catalog.GetString(" -- ");
			this.pnlRuralUsed.Add(this.lblTypeBUsedVal);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.pnlRuralUsed[this.lblTypeBUsedVal]));
			w41.PackType = ((global::Gtk.PackType)(1));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			this.pnlRuralNumbers.Add(this.pnlRuralUsed);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.pnlRuralNumbers[this.pnlRuralUsed]));
			w42.Position = 0;
			w42.Expand = false;
			w42.Fill = false;
			// Container child pnlRuralNumbers.Gtk.Box+BoxChild
			this.pnlRuralFree = new global::Gtk.HBox();
			this.pnlRuralFree.Name = "pnlRuralFree";
			this.pnlRuralFree.Spacing = 6;
			// Container child pnlRuralFree.Gtk.Box+BoxChild
			this.lblTypeBFree = new global::Gtk.Label();
			this.lblTypeBFree.Name = "lblTypeBFree";
			this.lblTypeBFree.LabelProp = global::Mono.Unix.Catalog.GetString("Free:");
			this.pnlRuralFree.Add(this.lblTypeBFree);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.pnlRuralFree[this.lblTypeBFree]));
			w43.Position = 0;
			w43.Expand = false;
			w43.Fill = false;
			// Container child pnlRuralFree.Gtk.Box+BoxChild
			this.lblTypeBFreeVal = new global::Gtk.Label();
			this.lblTypeBFreeVal.Name = "lblTypeBFreeVal";
			this.lblTypeBFreeVal.LabelProp = global::Mono.Unix.Catalog.GetString(" -- ");
			this.pnlRuralFree.Add(this.lblTypeBFreeVal);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.pnlRuralFree[this.lblTypeBFreeVal]));
			w44.PackType = ((global::Gtk.PackType)(1));
			w44.Position = 1;
			w44.Expand = false;
			w44.Fill = false;
			this.pnlRuralNumbers.Add(this.pnlRuralFree);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.pnlRuralNumbers[this.pnlRuralFree]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			// Container child pnlRuralNumbers.Gtk.Box+BoxChild
			this.pnlRuralTotal = new global::Gtk.HBox();
			this.pnlRuralTotal.Name = "pnlRuralTotal";
			this.pnlRuralTotal.Spacing = 6;
			// Container child pnlRuralTotal.Gtk.Box+BoxChild
			this.lblTypeBLimit = new global::Gtk.Label();
			this.lblTypeBLimit.Name = "lblTypeBLimit";
			this.lblTypeBLimit.LabelProp = global::Mono.Unix.Catalog.GetString("Limit:");
			this.pnlRuralTotal.Add(this.lblTypeBLimit);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.pnlRuralTotal[this.lblTypeBLimit]));
			w46.Position = 0;
			w46.Expand = false;
			w46.Fill = false;
			// Container child pnlRuralTotal.Gtk.Box+BoxChild
			this.lblTypeBLimitVal = new global::Gtk.Label();
			this.lblTypeBLimitVal.Name = "lblTypeBLimitVal";
			this.lblTypeBLimitVal.LabelProp = global::Mono.Unix.Catalog.GetString(" -- ");
			this.pnlRuralTotal.Add(this.lblTypeBLimitVal);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.pnlRuralTotal[this.lblTypeBLimitVal]));
			w47.PackType = ((global::Gtk.PackType)(1));
			w47.Position = 1;
			w47.Expand = false;
			w47.Fill = false;
			this.pnlRuralNumbers.Add(this.pnlRuralTotal);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.pnlRuralNumbers[this.pnlRuralTotal]));
			w48.Position = 2;
			w48.Expand = false;
			w48.Fill = false;
			this.pnlTypeB.Add(this.pnlRuralNumbers);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.pnlTypeB[this.pnlRuralNumbers]));
			w49.Position = 0;
			w49.Expand = false;
			w49.Fill = false;
			// Container child pnlTypeB.Gtk.Box+BoxChild
			this.evnTypeB = new global::Gtk.EventBox();
			this.evnTypeB.Name = "evnTypeB";
			// Container child evnTypeB.Gtk.Container+ContainerChild
			this.pctTypeB = new global::Gtk.Image();
			this.pctTypeB.TooltipMarkup = "Graph representing your bandwidth usage.";
			this.pctTypeB.Name = "pctTypeB";
			this.evnTypeB.Add(this.pctTypeB);
			this.pnlTypeB.Add(this.evnTypeB);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.pnlTypeB[this.evnTypeB]));
			w51.Position = 1;
			this.pnlDisplays.Add(this.pnlTypeB);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.pnlDisplays[this.pnlTypeB]));
			w52.Position = 2;
			this.algnUsage.Add(this.pnlDisplays);
			this.gbUsage.Add(this.algnUsage);
			this.lblStatus = new global::Gtk.Label();
			this.lblStatus.Name = "lblStatus";
			this.lblStatus.Xalign = 0F;
			this.lblStatus.LabelProp = global::Mono.Unix.Catalog.GetString("Usage Levels");
			this.lblStatus.UseMarkup = true;
			this.gbUsage.LabelWidget = this.lblStatus;
			this.pnlDetails.Add(this.gbUsage);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.pnlDetails[this.gbUsage]));
			w55.Position = 1;
			w55.Padding = ((uint)(3));
			// Container child pnlDetails.Gtk.Box+BoxChild
			this.sbMainStatus = new global::Gtk.Statusbar();
			this.sbMainStatus.Name = "sbMainStatus";
			this.sbMainStatus.Spacing = 6;
			// Container child sbMainStatus.Gtk.Box+BoxChild
			this.pbMainStatus = new global::Gtk.ProgressBar();
			this.pbMainStatus.Name = "pbMainStatus";
			this.sbMainStatus.Add(this.pbMainStatus);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.sbMainStatus[this.pbMainStatus]));
			w56.Position = 1;
			// Container child sbMainStatus.Gtk.Box+BoxChild
			this.cmdNetTest = new global::Gtk.Button();
			this.cmdNetTest.CanFocus = true;
			this.cmdNetTest.Name = "cmdNetTest";
			this.cmdNetTest.UseUnderline = true;
			this.cmdNetTest.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w57 = new global::Gtk.Image();
			this.cmdNetTest.Image = w57;
			this.sbMainStatus.Add(this.cmdNetTest);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.sbMainStatus[this.cmdNetTest]));
			w58.Position = 2;
			w58.Expand = false;
			w58.Fill = false;
			// Container child sbMainStatus.Gtk.Box+BoxChild
			this.lblMainStatus = new global::Gtk.Label();
			this.lblMainStatus.Name = "lblMainStatus";
			this.lblMainStatus.SingleLineMode = true;
			this.sbMainStatus.Add(this.lblMainStatus);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.sbMainStatus[this.lblMainStatus]));
			w59.Position = 3;
			w59.Expand = false;
			w59.Fill = false;
			this.pnlDetails.Add(this.sbMainStatus);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.pnlDetails[this.sbMainStatus]));
			w60.Position = 2;
			w60.Expand = false;
			w60.Fill = false;
			this.Add(this.pnlDetails);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 455;
			this.DefaultHeight = 245;
			this.Show();
			this.cmdNetTest.Clicked += new global::System.EventHandler(this.cmdNetTest_Clicked);
		}
	}
}
