
// This file has been generated by the GUI designer. Do not modify.
namespace RestrictionTrackerGTK
{
	public partial class dlgConfig
	{
		private global::Gtk.HBox pnlConfig;
		private global::Gtk.Table pnlConfigFields;
		private global::Gtk.CheckButton chkBeta;
		private global::Gtk.CheckButton chkInvert;
		private global::Gtk.CheckButton chkScaleScreen;
		private global::Gtk.Label lblAccount;
		private global::Gtk.Label lblAccuracy;
		private global::Gtk.Label lblHistoryDir;
		private global::Gtk.Label lblInterval;
		private global::Gtk.Label lblKey;
		private global::Gtk.Label lblPassword;
		private global::Gtk.Label lblTimeout;
		private global::Gtk.HBox pnlAccuracy;
		private global::Gtk.SpinButton txtAccuracy;
		private global::Gtk.Label lblAccuracyScale;
		private global::Gtk.HBox pnlInterval;
		private global::Gtk.SpinButton txtInterval;
		private global::Gtk.Label lblIntervalScale;
		private global::Gtk.Label lblPurchaseKey;
		private global::Gtk.HBox pnlKey;
		private global::Gtk.Entry txtKey1;
		private global::Gtk.Entry txtKey2;
		private global::Gtk.Entry txtKey3;
		private global::Gtk.Entry txtKey4;
		private global::Gtk.Entry txtKey5;
		private global::Gtk.EventBox evnKeyState;
		private global::Gtk.Image pctKeyState;
		private global::Gtk.HBox pnlOverAlert;
		private global::Gtk.CheckButton chkOverAlert;
		private global::Gtk.SpinButton txtOverSize;
		private global::Gtk.Label lblOverSize;
		private global::Gtk.SpinButton txtOverTime;
		private global::Gtk.Label lblOverTime;
		private global::Gtk.HBox pnlPassword;
		private global::Gtk.Entry txtPassword;
		private global::Gtk.ToggleButton cmdPassDisplay;
		private global::Gtk.HBox pnlTimeout;
		private global::Gtk.SpinButton txtTimeout;
		private global::Gtk.Label lblTimeoutScale;
		private global::Gtk.Entry txtAccount;
		private global::Gtk.FileChooserButton txtHistoryDir;
		private global::Gtk.VBox pnlProxyConfig;
		private global::Gtk.EventBox evnSRT;
		private global::Gtk.Image pctSRT;
		private global::Gtk.Frame gbProxy;
		private global::Gtk.Alignment alignProxy;
		private global::Gtk.Table pnlProxy;
		private global::Gtk.ComboBox cmbProxyType;
		private global::Gtk.Label lblProxyAddr;
		private global::Gtk.Label lblProxyDomain;
		private global::Gtk.Label lblProxyPassword;
		private global::Gtk.Label lblProxyPort;
		private global::Gtk.Label lblProxyType;
		private global::Gtk.Label lblProxyUser;
		private global::Gtk.Entry txtProxyAddress;
		private global::Gtk.Entry txtProxyDomain;
		private global::Gtk.Entry txtProxyPassword;
		private global::Gtk.SpinButton txtProxyPort;
		private global::Gtk.Entry txtProxyUser;
		private global::Gtk.Label lblProxy;
		private global::Gtk.HBox pnlCustomize;
		private global::Gtk.Button cmdAlertStyle;
		private global::Gtk.Button cmdColors;
		private global::Gtk.Button cmdSave;
		private global::Gtk.Button cmdClose;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RestrictionTrackerGTK.dlgConfig
			this.Name = "RestrictionTrackerGTK.dlgConfig";
			this.Title = global::Mono.Unix.Catalog.GetString ("Satellite Restriction Tracker Configuration");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("RestrictionTrackerGTK.Resources.norm.ico");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Internal child RestrictionTrackerGTK.dlgConfig.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "pnlDialog";
			w1.BorderWidth = ((uint)(2));
			// Container child pnlDialog.Gtk.Box+BoxChild
			this.pnlConfig = new global::Gtk.HBox ();
			this.pnlConfig.Name = "pnlConfig";
			this.pnlConfig.Spacing = 6;
			// Container child pnlConfig.Gtk.Box+BoxChild
			this.pnlConfigFields = new global::Gtk.Table (((uint)(11)), ((uint)(2)), false);
			this.pnlConfigFields.Name = "pnlConfigFields";
			this.pnlConfigFields.RowSpacing = ((uint)(2));
			this.pnlConfigFields.ColumnSpacing = ((uint)(2));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.chkBeta = new global::Gtk.CheckButton ();
			this.chkBeta.TooltipMarkup = "Check for updates to BETA versions when you open the About window.";
			this.chkBeta.CanFocus = true;
			this.chkBeta.Name = "chkBeta";
			this.chkBeta.Label = global::Mono.Unix.Catalog.GetString ("Check for BETA updates");
			this.chkBeta.DrawIndicator = true;
			this.chkBeta.UseUnderline = true;
			this.pnlConfigFields.Add (this.chkBeta);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.chkBeta]));
			w2.TopAttach = ((uint)(10));
			w2.BottomAttach = ((uint)(11));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.chkInvert = new global::Gtk.CheckButton ();
			this.chkInvert.TooltipMarkup = "If your Upload and Download numbers appear to be swapped, check this box to invert their display.";
			this.chkInvert.CanFocus = true;
			this.chkInvert.Name = "chkInvert";
			this.chkInvert.Label = global::Mono.Unix.Catalog.GetString ("Invert Upload/Download numbers");
			this.chkInvert.DrawIndicator = true;
			this.chkInvert.UseUnderline = true;
			this.pnlConfigFields.Add (this.chkInvert);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.chkInvert]));
			w3.TopAttach = ((uint)(8));
			w3.BottomAttach = ((uint)(9));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.chkScaleScreen = new global::Gtk.CheckButton ();
			this.chkScaleScreen.TooltipMarkup = "Text in the main window of Satellite Restriction Tracker will scale to fit its size.";
			this.chkScaleScreen.CanFocus = true;
			this.chkScaleScreen.Name = "chkScaleScreen";
			this.chkScaleScreen.Label = global::Mono.Unix.Catalog.GetString ("Scale text to window size");
			this.chkScaleScreen.DrawIndicator = true;
			this.chkScaleScreen.UseUnderline = true;
			this.pnlConfigFields.Add (this.chkScaleScreen);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.chkScaleScreen]));
			w4.TopAttach = ((uint)(5));
			w4.BottomAttach = ((uint)(6));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.lblAccount = new global::Gtk.Label ();
			this.lblAccount.Name = "lblAccount";
			this.lblAccount.Xalign = 0F;
			this.lblAccount.LabelProp = global::Mono.Unix.Catalog.GetString ("E-Mail:");
			this.pnlConfigFields.Add (this.lblAccount);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.lblAccount]));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.lblAccuracy = new global::Gtk.Label ();
			this.lblAccuracy.Name = "lblAccuracy";
			this.lblAccuracy.Xalign = 0F;
			this.lblAccuracy.LabelProp = global::Mono.Unix.Catalog.GetString ("Usage Accuracy:");
			this.pnlConfigFields.Add (this.lblAccuracy);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.lblAccuracy]));
			w6.TopAttach = ((uint)(4));
			w6.BottomAttach = ((uint)(5));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.lblHistoryDir = new global::Gtk.Label ();
			this.lblHistoryDir.Name = "lblHistoryDir";
			this.lblHistoryDir.Xalign = 0F;
			this.lblHistoryDir.LabelProp = global::Mono.Unix.Catalog.GetString ("Data Directory:");
			this.pnlConfigFields.Add (this.lblHistoryDir);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.lblHistoryDir]));
			w7.TopAttach = ((uint)(6));
			w7.BottomAttach = ((uint)(7));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.lblInterval = new global::Gtk.Label ();
			this.lblInterval.Name = "lblInterval";
			this.lblInterval.Xalign = 0F;
			this.lblInterval.LabelProp = global::Mono.Unix.Catalog.GetString ("Update Interval:");
			this.pnlConfigFields.Add (this.lblInterval);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.lblInterval]));
			w8.TopAttach = ((uint)(3));
			w8.BottomAttach = ((uint)(4));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.lblKey = new global::Gtk.Label ();
			this.lblKey.Name = "lblKey";
			this.lblKey.Xalign = 0F;
			this.lblKey.LabelProp = global::Mono.Unix.Catalog.GetString ("Product Key:");
			this.pnlConfigFields.Add (this.lblKey);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.lblKey]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.lblPassword = new global::Gtk.Label ();
			this.lblPassword.Name = "lblPassword";
			this.lblPassword.Xalign = 0F;
			this.lblPassword.LabelProp = global::Mono.Unix.Catalog.GetString ("Password:");
			this.pnlConfigFields.Add (this.lblPassword);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.lblPassword]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.lblTimeout = new global::Gtk.Label ();
			this.lblTimeout.Name = "lblTimeout";
			this.lblTimeout.Xalign = 0F;
			this.lblTimeout.LabelProp = global::Mono.Unix.Catalog.GetString ("Network Timeout:");
			this.pnlConfigFields.Add (this.lblTimeout);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.lblTimeout]));
			w11.TopAttach = ((uint)(7));
			w11.BottomAttach = ((uint)(8));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.pnlAccuracy = new global::Gtk.HBox ();
			this.pnlAccuracy.Name = "pnlAccuracy";
			this.pnlAccuracy.Spacing = 6;
			// Container child pnlAccuracy.Gtk.Box+BoxChild
			this.txtAccuracy = new global::Gtk.SpinButton (0, 4, 1);
			this.txtAccuracy.TooltipMarkup = "Number of decimal places to display.";
			this.txtAccuracy.CanFocus = true;
			this.txtAccuracy.Name = "txtAccuracy";
			this.txtAccuracy.Adjustment.PageIncrement = 1;
			this.txtAccuracy.ClimbRate = 1;
			this.txtAccuracy.Numeric = true;
			this.pnlAccuracy.Add (this.txtAccuracy);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.pnlAccuracy [this.txtAccuracy]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child pnlAccuracy.Gtk.Box+BoxChild
			this.lblAccuracyScale = new global::Gtk.Label ();
			this.lblAccuracyScale.Name = "lblAccuracyScale";
			this.lblAccuracyScale.LabelProp = global::Mono.Unix.Catalog.GetString ("decimal places");
			this.pnlAccuracy.Add (this.lblAccuracyScale);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.pnlAccuracy [this.lblAccuracyScale]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.pnlConfigFields.Add (this.pnlAccuracy);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.pnlAccuracy]));
			w14.TopAttach = ((uint)(4));
			w14.BottomAttach = ((uint)(5));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.pnlInterval = new global::Gtk.HBox ();
			this.pnlInterval.Name = "pnlInterval";
			this.pnlInterval.Spacing = 6;
			// Container child pnlInterval.Gtk.Box+BoxChild
			this.txtInterval = new global::Gtk.SpinButton (15, 1440, 1);
			this.txtInterval.TooltipMarkup = "Interval between bandwidth checks in minutes.";
			this.txtInterval.CanFocus = true;
			this.txtInterval.Name = "txtInterval";
			this.txtInterval.Adjustment.PageIncrement = 5;
			this.txtInterval.ClimbRate = 1;
			this.txtInterval.Numeric = true;
			this.txtInterval.Value = 15;
			this.pnlInterval.Add (this.txtInterval);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.pnlInterval [this.txtInterval]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child pnlInterval.Gtk.Box+BoxChild
			this.lblIntervalScale = new global::Gtk.Label ();
			this.lblIntervalScale.Name = "lblIntervalScale";
			this.lblIntervalScale.Xalign = 0F;
			this.lblIntervalScale.LabelProp = global::Mono.Unix.Catalog.GetString ("minutes");
			this.pnlInterval.Add (this.lblIntervalScale);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.pnlInterval [this.lblIntervalScale]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child pnlInterval.Gtk.Box+BoxChild
			this.lblPurchaseKey = new global::Gtk.Label ();
			this.lblPurchaseKey.CanFocus = true;
			this.lblPurchaseKey.Name = "lblPurchaseKey";
			this.lblPurchaseKey.Xalign = 1F;
			this.lblPurchaseKey.Yalign = 0F;
			this.lblPurchaseKey.LabelProp = global::Mono.Unix.Catalog.GetString ("Purchase a Key");
			this.pnlInterval.Add (this.lblPurchaseKey);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.pnlInterval [this.lblPurchaseKey]));
			w17.Position = 2;
			this.pnlConfigFields.Add (this.pnlInterval);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.pnlInterval]));
			w18.TopAttach = ((uint)(3));
			w18.BottomAttach = ((uint)(4));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.pnlKey = new global::Gtk.HBox ();
			this.pnlKey.Name = "pnlKey";
			this.pnlKey.Spacing = 6;
			// Container child pnlKey.Gtk.Box+BoxChild
			this.txtKey1 = new global::Gtk.Entry ();
			this.txtKey1.TooltipMarkup = "Your Remote Usage Service Product Key.";
			this.txtKey1.CanFocus = true;
			this.txtKey1.Name = "txtKey1";
			this.txtKey1.IsEditable = true;
			this.txtKey1.WidthChars = 7;
			this.txtKey1.MaxLength = 6;
			this.txtKey1.InvisibleChar = '●';
			this.txtKey1.Xalign = 0.5F;
			this.pnlKey.Add (this.txtKey1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.pnlKey [this.txtKey1]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child pnlKey.Gtk.Box+BoxChild
			this.txtKey2 = new global::Gtk.Entry ();
			this.txtKey2.TooltipMarkup = "Your Remote Usage Service Product Key.";
			this.txtKey2.CanFocus = true;
			this.txtKey2.Name = "txtKey2";
			this.txtKey2.IsEditable = true;
			this.txtKey2.WidthChars = 5;
			this.txtKey2.MaxLength = 4;
			this.txtKey2.InvisibleChar = '●';
			this.txtKey2.Xalign = 0.5F;
			this.pnlKey.Add (this.txtKey2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.pnlKey [this.txtKey2]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child pnlKey.Gtk.Box+BoxChild
			this.txtKey3 = new global::Gtk.Entry ();
			this.txtKey3.TooltipMarkup = "Your Remote Usage Service Product Key.";
			this.txtKey3.CanFocus = true;
			this.txtKey3.Name = "txtKey3";
			this.txtKey3.IsEditable = true;
			this.txtKey3.WidthChars = 5;
			this.txtKey3.MaxLength = 4;
			this.txtKey3.InvisibleChar = '●';
			this.txtKey3.Xalign = 0.5F;
			this.pnlKey.Add (this.txtKey3);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.pnlKey [this.txtKey3]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			// Container child pnlKey.Gtk.Box+BoxChild
			this.txtKey4 = new global::Gtk.Entry ();
			this.txtKey4.TooltipMarkup = "Your Remote Usage Service Product Key.";
			this.txtKey4.CanFocus = true;
			this.txtKey4.Name = "txtKey4";
			this.txtKey4.IsEditable = true;
			this.txtKey4.WidthChars = 5;
			this.txtKey4.MaxLength = 4;
			this.txtKey4.InvisibleChar = '●';
			this.txtKey4.Xalign = 0.5F;
			this.pnlKey.Add (this.txtKey4);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.pnlKey [this.txtKey4]));
			w22.Position = 3;
			w22.Expand = false;
			w22.Fill = false;
			// Container child pnlKey.Gtk.Box+BoxChild
			this.txtKey5 = new global::Gtk.Entry ();
			this.txtKey5.TooltipMarkup = "Your Remote Usage Service Product Key.";
			this.txtKey5.CanFocus = true;
			this.txtKey5.Name = "txtKey5";
			this.txtKey5.IsEditable = true;
			this.txtKey5.WidthChars = 7;
			this.txtKey5.MaxLength = 6;
			this.txtKey5.InvisibleChar = '●';
			this.txtKey5.Xalign = 0.5F;
			this.pnlKey.Add (this.txtKey5);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.pnlKey [this.txtKey5]));
			w23.Position = 4;
			w23.Expand = false;
			w23.Fill = false;
			// Container child pnlKey.Gtk.Box+BoxChild
			this.evnKeyState = new global::Gtk.EventBox ();
			this.evnKeyState.Name = "evnKeyState";
			// Container child evnKeyState.Gtk.Container+ContainerChild
			this.pctKeyState = new global::Gtk.Image ();
			this.pctKeyState.WidthRequest = 16;
			this.pctKeyState.HeightRequest = 16;
			this.pctKeyState.Name = "pctKeyState";
			this.pctKeyState.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("RestrictionTrackerGTK.Resources.error.png");
			this.evnKeyState.Add (this.pctKeyState);
			this.pnlKey.Add (this.evnKeyState);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.pnlKey [this.evnKeyState]));
			w25.Position = 5;
			this.pnlConfigFields.Add (this.pnlKey);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.pnlKey]));
			w26.TopAttach = ((uint)(2));
			w26.BottomAttach = ((uint)(3));
			w26.LeftAttach = ((uint)(1));
			w26.RightAttach = ((uint)(2));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.pnlOverAlert = new global::Gtk.HBox ();
			this.pnlOverAlert.Name = "pnlOverAlert";
			this.pnlOverAlert.Spacing = 6;
			// Container child pnlOverAlert.Gtk.Box+BoxChild
			this.chkOverAlert = new global::Gtk.CheckButton ();
			this.chkOverAlert.TooltipMarkup = "Check this box to display an alert when you use too much bandwidth.";
			this.chkOverAlert.CanFocus = true;
			this.chkOverAlert.Name = "chkOverAlert";
			this.chkOverAlert.Label = global::Mono.Unix.Catalog.GetString ("Bandwidth Alert");
			this.chkOverAlert.DrawIndicator = true;
			this.chkOverAlert.UseUnderline = true;
			this.pnlOverAlert.Add (this.chkOverAlert);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.pnlOverAlert [this.chkOverAlert]));
			w27.Position = 0;
			// Container child pnlOverAlert.Gtk.Box+BoxChild
			this.txtOverSize = new global::Gtk.SpinButton (25, 5000, 1);
			this.txtOverSize.TooltipMarkup = "Enter the amount of bandwidth usage to display an alert about (in Megabytes).";
			this.txtOverSize.CanFocus = true;
			this.txtOverSize.Name = "txtOverSize";
			this.txtOverSize.Adjustment.PageIncrement = 100;
			this.txtOverSize.ClimbRate = 1;
			this.txtOverSize.Numeric = true;
			this.txtOverSize.Value = 100;
			this.pnlOverAlert.Add (this.txtOverSize);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.pnlOverAlert [this.txtOverSize]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child pnlOverAlert.Gtk.Box+BoxChild
			this.lblOverSize = new global::Gtk.Label ();
			this.lblOverSize.Name = "lblOverSize";
			this.lblOverSize.LabelProp = global::Mono.Unix.Catalog.GetString ("MB in");
			this.pnlOverAlert.Add (this.lblOverSize);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.pnlOverAlert [this.lblOverSize]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			// Container child pnlOverAlert.Gtk.Box+BoxChild
			this.txtOverTime = new global::Gtk.SpinButton (15, 360, 1);
			this.txtOverTime.TooltipMarkup = "Enter the duration of time to check for the defined bandwidth usage (in minutes).";
			this.txtOverTime.CanFocus = true;
			this.txtOverTime.Name = "txtOverTime";
			this.txtOverTime.Adjustment.PageIncrement = 15;
			this.txtOverTime.ClimbRate = 1;
			this.txtOverTime.Numeric = true;
			this.txtOverTime.Value = 15;
			this.pnlOverAlert.Add (this.txtOverTime);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.pnlOverAlert [this.txtOverTime]));
			w30.Position = 3;
			w30.Expand = false;
			w30.Fill = false;
			// Container child pnlOverAlert.Gtk.Box+BoxChild
			this.lblOverTime = new global::Gtk.Label ();
			this.lblOverTime.Name = "lblOverTime";
			this.lblOverTime.LabelProp = global::Mono.Unix.Catalog.GetString ("minutes");
			this.pnlOverAlert.Add (this.lblOverTime);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.pnlOverAlert [this.lblOverTime]));
			w31.Position = 4;
			w31.Expand = false;
			w31.Fill = false;
			this.pnlConfigFields.Add (this.pnlOverAlert);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.pnlOverAlert]));
			w32.TopAttach = ((uint)(9));
			w32.BottomAttach = ((uint)(10));
			w32.RightAttach = ((uint)(2));
			w32.XOptions = ((global::Gtk.AttachOptions)(7));
			w32.YOptions = ((global::Gtk.AttachOptions)(6));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.pnlPassword = new global::Gtk.HBox ();
			this.pnlPassword.Name = "pnlPassword";
			this.pnlPassword.Spacing = 6;
			// Container child pnlPassword.Gtk.Box+BoxChild
			this.txtPassword = new global::Gtk.Entry ();
			this.txtPassword.TooltipMarkup = "The password to your ViaSat account.";
			this.txtPassword.CanFocus = true;
			this.txtPassword.Name = "txtPassword";
			this.txtPassword.IsEditable = true;
			this.txtPassword.InvisibleChar = '●';
			this.pnlPassword.Add (this.txtPassword);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.pnlPassword [this.txtPassword]));
			w33.Position = 0;
			// Container child pnlPassword.Gtk.Box+BoxChild
			this.cmdPassDisplay = new global::Gtk.ToggleButton ();
			this.cmdPassDisplay.TooltipMarkup = "Toggle display of the password.";
			this.cmdPassDisplay.CanFocus = true;
			this.cmdPassDisplay.Name = "cmdPassDisplay";
			this.cmdPassDisplay.UseUnderline = true;
			this.cmdPassDisplay.Active = true;
			// Container child cmdPassDisplay.Gtk.Container+ContainerChild
			global::Gtk.Alignment w34 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w35 = new global::Gtk.HBox ();
			w35.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w36 = new global::Gtk.Image ();
			w36.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-authentication", global::Gtk.IconSize.Button);
			w35.Add (w36);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w38 = new global::Gtk.Label ();
			w35.Add (w38);
			w34.Add (w35);
			this.cmdPassDisplay.Add (w34);
			this.pnlPassword.Add (this.cmdPassDisplay);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.pnlPassword [this.cmdPassDisplay]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			this.pnlConfigFields.Add (this.pnlPassword);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.pnlPassword]));
			w43.TopAttach = ((uint)(1));
			w43.BottomAttach = ((uint)(2));
			w43.LeftAttach = ((uint)(1));
			w43.RightAttach = ((uint)(2));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.pnlTimeout = new global::Gtk.HBox ();
			this.pnlTimeout.Name = "pnlTimeout";
			this.pnlTimeout.Spacing = 6;
			// Container child pnlTimeout.Gtk.Box+BoxChild
			this.txtTimeout = new global::Gtk.SpinButton (5, 600, 1);
			this.txtTimeout.TooltipMarkup = "Number of seconds to wait between network communications.";
			this.txtTimeout.CanFocus = true;
			this.txtTimeout.Name = "txtTimeout";
			this.txtTimeout.Adjustment.PageIncrement = 15;
			this.txtTimeout.ClimbRate = 1;
			this.txtTimeout.Numeric = true;
			this.txtTimeout.Value = 60;
			this.pnlTimeout.Add (this.txtTimeout);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.pnlTimeout [this.txtTimeout]));
			w44.Position = 0;
			w44.Expand = false;
			w44.Fill = false;
			// Container child pnlTimeout.Gtk.Box+BoxChild
			this.lblTimeoutScale = new global::Gtk.Label ();
			this.lblTimeoutScale.Name = "lblTimeoutScale";
			this.lblTimeoutScale.LabelProp = global::Mono.Unix.Catalog.GetString ("seconds");
			this.pnlTimeout.Add (this.lblTimeoutScale);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.pnlTimeout [this.lblTimeoutScale]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			this.pnlConfigFields.Add (this.pnlTimeout);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.pnlTimeout]));
			w46.TopAttach = ((uint)(7));
			w46.BottomAttach = ((uint)(8));
			w46.LeftAttach = ((uint)(1));
			w46.RightAttach = ((uint)(2));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.txtAccount = new global::Gtk.Entry ();
			this.txtAccount.TooltipMarkup = "Your ViaSat E-Mail address.";
			this.txtAccount.CanFocus = true;
			this.txtAccount.Name = "txtAccount";
			this.txtAccount.IsEditable = true;
			this.txtAccount.InvisibleChar = '●';
			this.pnlConfigFields.Add (this.txtAccount);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.txtAccount]));
			w47.LeftAttach = ((uint)(1));
			w47.RightAttach = ((uint)(2));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlConfigFields.Gtk.Table+TableChild
			this.txtHistoryDir = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a Directory"), ((global::Gtk.FileChooserAction)(2)));
			this.txtHistoryDir.TooltipMarkup = "Directory used to save History Data.";
			this.txtHistoryDir.Name = "txtHistoryDir";
			this.txtHistoryDir.ShowHidden = true;
			this.pnlConfigFields.Add (this.txtHistoryDir);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.pnlConfigFields [this.txtHistoryDir]));
			w48.TopAttach = ((uint)(6));
			w48.BottomAttach = ((uint)(7));
			w48.LeftAttach = ((uint)(1));
			w48.RightAttach = ((uint)(2));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			this.pnlConfig.Add (this.pnlConfigFields);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.pnlConfig [this.pnlConfigFields]));
			w49.Position = 0;
			w49.Expand = false;
			w49.Fill = false;
			// Container child pnlConfig.Gtk.Box+BoxChild
			this.pnlProxyConfig = new global::Gtk.VBox ();
			this.pnlProxyConfig.Name = "pnlProxyConfig";
			this.pnlProxyConfig.Spacing = 2;
			// Container child pnlProxyConfig.Gtk.Box+BoxChild
			this.evnSRT = new global::Gtk.EventBox ();
			this.evnSRT.Name = "evnSRT";
			// Container child evnSRT.Gtk.Container+ContainerChild
			this.pctSRT = new global::Gtk.Image ();
			this.pctSRT.Name = "pctSRT";
			this.evnSRT.Add (this.pctSRT);
			this.pnlProxyConfig.Add (this.evnSRT);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.pnlProxyConfig [this.evnSRT]));
			w51.Position = 0;
			w51.Expand = false;
			w51.Fill = false;
			// Container child pnlProxyConfig.Gtk.Box+BoxChild
			this.gbProxy = new global::Gtk.Frame ();
			this.gbProxy.Name = "gbProxy";
			// Container child gbProxy.Gtk.Container+ContainerChild
			this.alignProxy = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.alignProxy.Name = "alignProxy";
			this.alignProxy.LeftPadding = ((uint)(3));
			this.alignProxy.TopPadding = ((uint)(3));
			this.alignProxy.RightPadding = ((uint)(3));
			this.alignProxy.BottomPadding = ((uint)(3));
			// Container child alignProxy.Gtk.Container+ContainerChild
			this.pnlProxy = new global::Gtk.Table (((uint)(7)), ((uint)(2)), false);
			this.pnlProxy.Name = "pnlProxy";
			this.pnlProxy.RowSpacing = ((uint)(2));
			this.pnlProxy.ColumnSpacing = ((uint)(2));
			// Container child pnlProxy.Gtk.Table+TableChild
			this.cmbProxyType = global::Gtk.ComboBox.NewText ();
			this.cmbProxyType.AppendText (global::Mono.Unix.Catalog.GetString ("None"));
			this.cmbProxyType.AppendText (global::Mono.Unix.Catalog.GetString ("System"));
			this.cmbProxyType.AppendText (global::Mono.Unix.Catalog.GetString ("IP"));
			this.cmbProxyType.AppendText (global::Mono.Unix.Catalog.GetString ("URL"));
			this.cmbProxyType.TooltipMarkup = "Type of Proxy to Use\n <b>None:</b> No Proxy\n <b>System:</b> Default System Proxy Settings\n <b>IP:</b> HTTP Proxy by IP Address and Port\n <b>URL:</b> HTTP Proxy by Web URL";
			this.cmbProxyType.Name = "cmbProxyType";
			this.cmbProxyType.Active = 0;
			this.pnlProxy.Add (this.cmbProxyType);
			global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.pnlProxy [this.cmbProxyType]));
			w52.LeftAttach = ((uint)(1));
			w52.RightAttach = ((uint)(2));
			w52.XOptions = ((global::Gtk.AttachOptions)(4));
			w52.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlProxy.Gtk.Table+TableChild
			this.lblProxyAddr = new global::Gtk.Label ();
			this.lblProxyAddr.Name = "lblProxyAddr";
			this.lblProxyAddr.Xalign = 0F;
			this.lblProxyAddr.LabelProp = global::Mono.Unix.Catalog.GetString ("IP Address:");
			this.pnlProxy.Add (this.lblProxyAddr);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.pnlProxy [this.lblProxyAddr]));
			w53.TopAttach = ((uint)(1));
			w53.BottomAttach = ((uint)(2));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlProxy.Gtk.Table+TableChild
			this.lblProxyDomain = new global::Gtk.Label ();
			this.lblProxyDomain.Name = "lblProxyDomain";
			this.lblProxyDomain.Xalign = 0F;
			this.lblProxyDomain.LabelProp = global::Mono.Unix.Catalog.GetString ("Domain:");
			this.pnlProxy.Add (this.lblProxyDomain);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.pnlProxy [this.lblProxyDomain]));
			w54.TopAttach = ((uint)(5));
			w54.BottomAttach = ((uint)(6));
			w54.RightAttach = ((uint)(2));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlProxy.Gtk.Table+TableChild
			this.lblProxyPassword = new global::Gtk.Label ();
			this.lblProxyPassword.Name = "lblProxyPassword";
			this.lblProxyPassword.Xalign = 0F;
			this.lblProxyPassword.LabelProp = global::Mono.Unix.Catalog.GetString ("Password:");
			this.pnlProxy.Add (this.lblProxyPassword);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.pnlProxy [this.lblProxyPassword]));
			w55.TopAttach = ((uint)(3));
			w55.BottomAttach = ((uint)(4));
			w55.LeftAttach = ((uint)(1));
			w55.RightAttach = ((uint)(2));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlProxy.Gtk.Table+TableChild
			this.lblProxyPort = new global::Gtk.Label ();
			this.lblProxyPort.Name = "lblProxyPort";
			this.lblProxyPort.Xalign = 0F;
			this.lblProxyPort.LabelProp = global::Mono.Unix.Catalog.GetString ("Port:");
			this.pnlProxy.Add (this.lblProxyPort);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.pnlProxy [this.lblProxyPort]));
			w56.TopAttach = ((uint)(1));
			w56.BottomAttach = ((uint)(2));
			w56.LeftAttach = ((uint)(1));
			w56.RightAttach = ((uint)(2));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlProxy.Gtk.Table+TableChild
			this.lblProxyType = new global::Gtk.Label ();
			this.lblProxyType.Name = "lblProxyType";
			this.lblProxyType.Xalign = 0F;
			this.lblProxyType.LabelProp = global::Mono.Unix.Catalog.GetString ("Proxy Type:");
			this.pnlProxy.Add (this.lblProxyType);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.pnlProxy [this.lblProxyType]));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlProxy.Gtk.Table+TableChild
			this.lblProxyUser = new global::Gtk.Label ();
			this.lblProxyUser.Name = "lblProxyUser";
			this.lblProxyUser.Xalign = 0F;
			this.lblProxyUser.LabelProp = global::Mono.Unix.Catalog.GetString ("Username:");
			this.pnlProxy.Add (this.lblProxyUser);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.pnlProxy [this.lblProxyUser]));
			w58.TopAttach = ((uint)(3));
			w58.BottomAttach = ((uint)(4));
			w58.XOptions = ((global::Gtk.AttachOptions)(4));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlProxy.Gtk.Table+TableChild
			this.txtProxyAddress = new global::Gtk.Entry ();
			this.txtProxyAddress.TooltipMarkup = "Address of HTTP Proxy to connect through.";
			this.txtProxyAddress.CanFocus = true;
			this.txtProxyAddress.Name = "txtProxyAddress";
			this.txtProxyAddress.IsEditable = true;
			this.txtProxyAddress.WidthChars = 15;
			this.txtProxyAddress.InvisibleChar = '●';
			this.pnlProxy.Add (this.txtProxyAddress);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.pnlProxy [this.txtProxyAddress]));
			w59.TopAttach = ((uint)(2));
			w59.BottomAttach = ((uint)(3));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlProxy.Gtk.Table+TableChild
			this.txtProxyDomain = new global::Gtk.Entry ();
			this.txtProxyDomain.TooltipMarkup = "Optional Domain for HTTP Proxy authentication.";
			this.txtProxyDomain.CanFocus = true;
			this.txtProxyDomain.Name = "txtProxyDomain";
			this.txtProxyDomain.IsEditable = true;
			this.txtProxyDomain.InvisibleChar = '●';
			this.pnlProxy.Add (this.txtProxyDomain);
			global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.pnlProxy [this.txtProxyDomain]));
			w60.TopAttach = ((uint)(6));
			w60.BottomAttach = ((uint)(7));
			w60.RightAttach = ((uint)(2));
			w60.XOptions = ((global::Gtk.AttachOptions)(4));
			w60.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlProxy.Gtk.Table+TableChild
			this.txtProxyPassword = new global::Gtk.Entry ();
			this.txtProxyPassword.TooltipMarkup = "Optional Password for HTTP Proxy authentication.";
			this.txtProxyPassword.CanFocus = true;
			this.txtProxyPassword.Name = "txtProxyPassword";
			this.txtProxyPassword.IsEditable = true;
			this.txtProxyPassword.WidthChars = 15;
			this.txtProxyPassword.InvisibleChar = '●';
			this.pnlProxy.Add (this.txtProxyPassword);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.pnlProxy [this.txtProxyPassword]));
			w61.TopAttach = ((uint)(4));
			w61.BottomAttach = ((uint)(5));
			w61.LeftAttach = ((uint)(1));
			w61.RightAttach = ((uint)(2));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlProxy.Gtk.Table+TableChild
			this.txtProxyPort = new global::Gtk.SpinButton (1, 65535, 1);
			this.txtProxyPort.TooltipMarkup = "Port to connect to HTTP proxy over.";
			this.txtProxyPort.CanFocus = true;
			this.txtProxyPort.Name = "txtProxyPort";
			this.txtProxyPort.Adjustment.PageIncrement = 10;
			this.txtProxyPort.ClimbRate = 1;
			this.txtProxyPort.Numeric = true;
			this.txtProxyPort.Value = 8080;
			this.pnlProxy.Add (this.txtProxyPort);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.pnlProxy [this.txtProxyPort]));
			w62.TopAttach = ((uint)(2));
			w62.BottomAttach = ((uint)(3));
			w62.LeftAttach = ((uint)(1));
			w62.RightAttach = ((uint)(2));
			w62.XOptions = ((global::Gtk.AttachOptions)(0));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlProxy.Gtk.Table+TableChild
			this.txtProxyUser = new global::Gtk.Entry ();
			this.txtProxyUser.TooltipMarkup = "Optional Username for HTTP Proxy authentication.";
			this.txtProxyUser.CanFocus = true;
			this.txtProxyUser.Name = "txtProxyUser";
			this.txtProxyUser.IsEditable = true;
			this.txtProxyUser.WidthChars = 15;
			this.txtProxyUser.InvisibleChar = '●';
			this.pnlProxy.Add (this.txtProxyUser);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.pnlProxy [this.txtProxyUser]));
			w63.TopAttach = ((uint)(4));
			w63.BottomAttach = ((uint)(5));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			this.alignProxy.Add (this.pnlProxy);
			this.gbProxy.Add (this.alignProxy);
			this.lblProxy = new global::Gtk.Label ();
			this.lblProxy.Name = "lblProxy";
			this.lblProxy.LabelProp = global::Mono.Unix.Catalog.GetString ("HTTP Proxy");
			this.lblProxy.UseMarkup = true;
			this.gbProxy.LabelWidget = this.lblProxy;
			this.pnlProxyConfig.Add (this.gbProxy);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.pnlProxyConfig [this.gbProxy]));
			w66.Position = 2;
			w66.Expand = false;
			w66.Fill = false;
			w66.Padding = ((uint)(3));
			// Container child pnlProxyConfig.Gtk.Box+BoxChild
			this.pnlCustomize = new global::Gtk.HBox ();
			this.pnlCustomize.Name = "pnlCustomize";
			this.pnlCustomize.Homogeneous = true;
			this.pnlCustomize.Spacing = 6;
			// Container child pnlCustomize.Gtk.Box+BoxChild
			this.cmdAlertStyle = new global::Gtk.Button ();
			this.cmdAlertStyle.CanFocus = true;
			this.cmdAlertStyle.Name = "cmdAlertStyle";
			this.cmdAlertStyle.UseUnderline = true;
			// Container child cmdAlertStyle.Gtk.Container+ContainerChild
			global::Gtk.Alignment w67 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w68 = new global::Gtk.HBox ();
			w68.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w69 = new global::Gtk.Image ();
			w69.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-select-font", global::Gtk.IconSize.Button);
			w68.Add (w69);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w71 = new global::Gtk.Label ();
			w71.LabelProp = global::Mono.Unix.Catalog.GetString ("Set Alert Style");
			w71.UseUnderline = true;
			w68.Add (w71);
			w67.Add (w68);
			this.cmdAlertStyle.Add (w67);
			this.pnlCustomize.Add (this.cmdAlertStyle);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.pnlCustomize [this.cmdAlertStyle]));
			w75.Position = 0;
			w75.Expand = false;
			w75.Fill = false;
			// Container child pnlCustomize.Gtk.Box+BoxChild
			this.cmdColors = new global::Gtk.Button ();
			this.cmdColors.TooltipMarkup = "Change the colors of the Main Window, Tray Icon, and History Graphs.";
			this.cmdColors.CanFocus = true;
			this.cmdColors.Name = "cmdColors";
			this.cmdColors.UseUnderline = true;
			// Container child cmdColors.Gtk.Container+ContainerChild
			global::Gtk.Alignment w76 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w77 = new global::Gtk.HBox ();
			w77.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w78 = new global::Gtk.Image ();
			w78.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-select-color", global::Gtk.IconSize.Button);
			w77.Add (w78);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w80 = new global::Gtk.Label ();
			w80.LabelProp = global::Mono.Unix.Catalog.GetString ("Graph _Colors");
			w80.UseUnderline = true;
			w77.Add (w80);
			w76.Add (w77);
			this.cmdColors.Add (w76);
			this.pnlCustomize.Add (this.cmdColors);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.pnlCustomize [this.cmdColors]));
			w84.Position = 1;
			w84.Expand = false;
			w84.Fill = false;
			this.pnlProxyConfig.Add (this.pnlCustomize);
			global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.pnlProxyConfig [this.pnlCustomize]));
			w85.Position = 4;
			w85.Expand = false;
			w85.Fill = false;
			this.pnlConfig.Add (this.pnlProxyConfig);
			global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.pnlConfig [this.pnlProxyConfig]));
			w86.Position = 1;
			w1.Add (this.pnlConfig);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(w1 [this.pnlConfig]));
			w87.Position = 0;
			w87.Expand = false;
			w87.Fill = false;
			// Internal child RestrictionTrackerGTK.dlgConfig.ActionArea
			global::Gtk.HButtonBox w88 = this.ActionArea;
			w88.Name = "pnlConfigButtons";
			w88.Spacing = 10;
			w88.BorderWidth = ((uint)(5));
			w88.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child pnlConfigButtons.Gtk.ButtonBox+ButtonBoxChild
			this.cmdSave = new global::Gtk.Button ();
			this.cmdSave.TooltipMarkup = "Save Changes to the Configuration.";
			this.cmdSave.CanDefault = true;
			this.cmdSave.CanFocus = true;
			this.cmdSave.Name = "cmdSave";
			this.cmdSave.UseUnderline = true;
			// Container child cmdSave.Gtk.Container+ContainerChild
			global::Gtk.Alignment w89 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w90 = new global::Gtk.HBox ();
			w90.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w91 = new global::Gtk.Image ();
			w91.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save", global::Gtk.IconSize.Button);
			w90.Add (w91);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w93 = new global::Gtk.Label ();
			w93.LabelProp = global::Mono.Unix.Catalog.GetString ("_Save");
			w93.UseUnderline = true;
			w90.Add (w93);
			w89.Add (w90);
			this.cmdSave.Add (w89);
			w88.Add (this.cmdSave);
			global::Gtk.ButtonBox.ButtonBoxChild w97 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w88 [this.cmdSave]));
			w97.Expand = false;
			w97.Fill = false;
			// Container child pnlConfigButtons.Gtk.ButtonBox+ButtonBoxChild
			this.cmdClose = new global::Gtk.Button ();
			this.cmdClose.TooltipMarkup = "Close the Configuration window.";
			this.cmdClose.CanDefault = true;
			this.cmdClose.CanFocus = true;
			this.cmdClose.Name = "cmdClose";
			this.cmdClose.UseUnderline = true;
			// Container child cmdClose.Gtk.Container+ContainerChild
			global::Gtk.Alignment w98 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w99 = new global::Gtk.HBox ();
			w99.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w100 = new global::Gtk.Image ();
			w100.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Button);
			w99.Add (w100);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w102 = new global::Gtk.Label ();
			w102.LabelProp = global::Mono.Unix.Catalog.GetString ("_Close");
			w102.UseUnderline = true;
			w99.Add (w102);
			w98.Add (w99);
			this.cmdClose.Add (w98);
			this.AddActionWidget (this.cmdClose, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w106 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w88 [this.cmdClose]));
			w106.Position = 1;
			w106.Expand = false;
			w106.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 642;
			this.DefaultHeight = 336;
			this.Hide ();
		}
	}
}
